// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 1
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) Xzero_everything() {
	binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(i32_const(0)))
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(4)):], uint32(i32_const(0)))
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(i32_const(0)))
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(12)):], uint32(i32_const(0)))
}
func (m *Module) Xtest_store_to_load() int32 {
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(i32_const(0)))
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(5)):], math.Float32bits(math.Float32frombits(2147483648)))
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(8)):]))
	return t0
}
func (m *Module) Xtest_redundant_load() int32 {
	var v0, v1 int32
	_, _ = v0, v1
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(8)):]))
	v0 = t0
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(5)):], uint32(i32_const(-2147483648)))
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(8)):]))
	v1 = t1
	t2 := v0
	t3 := v1
	t4 := t2 + t3
	return t4
}
func (m *Module) Xtest_dead_store() float32 {
	var v0 float32
	_ = v0
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(i32_const(589505315)))
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(int32(11)):]))
	v0 = t0
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(i32_const(0)))
	t1 := v0
	return t1
}
func (m *Module) Xmalloc(v0 int32) int32 {
	return int32(16)
}
func (m *Module) Xmalloc_aliasing() int32 {
	var v0, v1 int32
	_, _ = v0, v1
	t0 := m.Xmalloc(int32(4))
	v0 = t0
	t1 := m.Xmalloc(int32(4))
	v1 = t1
	t2 := v0
	binary.LittleEndian.PutUint32(m.memory[uint32(t2):], uint32(int32(42)))
	t3 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t3):], uint32(int32(43)))
	t4 := v0
	t5 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t4):]))
	return t5
}

//go:nosplit
func i32_const(x int32) int32 { return x }
