// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_epsilon_3u62dj() float32 {
	return float32(f32_const(1) - float32(float32(3)*float32(float32(float32(4)/float32(3))-f32_const(1))))
}
func (m *Module) Xf64_epsilon_1nkgelz() float64 {
	return float64(f64_const(1) - float64(float64(3)*float64(float64(float64(4)/float64(3))-f64_const(1))))
}

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
