// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xno_demote_mixed_sub(v0 float64, v1 float32) float32 {
	return float32(float64(v0 - float64(v1)))
}
func (m *Module) Xno_demote_mixed_sub_commuted(v0 float32, v1 float64) float32 {
	return float32(float64(float64(v0) - v1))
}
