// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_recip_recip_1r42n7g(v0 float32) float32 {
	return float32(f32(1) / float32(f32(1)/v0))
}
func (m *Module) Xf64_no_fold_recip_recip_1rieeiv(v0 float64) float64 {
	return float64(f64(1) / float64(f64(1)/v0))
}

//go:nosplit
func f32(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
