// Code generated by wasm2go. DO NOT EDIT.

package tlsf

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	memory           []byte
	maxMem           int64
	___stack_pointer int32
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 0x20000)
	m.___stack_pointer = i32(65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xfree(v0 int32) {
	if v0 != 0 {
		if v0&i32(15) != 0 {
			goto l0
		}
		v0 = v0 - i32(4)
		t0 := int32(load32(m.memory[uint32(v0):]))
		if t0&i32(1) != 0 {
			goto l0
		}
		m._tlsf_block_free(v0)
	}
	return
l0:
	panic("unreachable")
}
func (m *Module) _tlsf_block_free(v0 int32) {
	var v1, v2, v3, v4, v5 int32
	t0 := m.___stack_pointer
	v4 = t0 - i32(16)
	m.___stack_pointer = v4
	t1 := int32(load32(m.memory[uint32(v0):]))
	t2 := v0
	v2 = t1
	v3 = t2 + v2&i32(-16)
	t3 := int32(load32(m.memory[uint32(v3):]))
	if t3&i32(1) != 0 {
		m._tlsf_remove_free_block(v3)
		t4 := int32(load32(m.memory[uint32(v3):]))
		t5 := int32(load32(m.memory[uint32(v0):]))
		t6 := t4 & i32(-16)
		v2 = t5
		v1 = t6 + v2&i32(-16)
		t7 := v0
		v2 = v1 | v2&i32(15)
		store32(m.memory[uint32(t7):], uint32(v2))
		v3 = v0 + v1
	}
	{
		if v2&i32(2) == 0 {
			v1 = v0
			goto l0
		}
		t8 := int32(load32(m.memory[uint32(v0-i32(4)):]))
		v1 = v0 - t8
		m._tlsf_remove_free_block(v1)
		t9 := int32(load32(m.memory[uint32(v0):]))
		t10 := int32(load32(m.memory[uint32(v1):]))
		t11 := v1
		t12 := t9 & i32(-16)
		v0 = t10
		v2 = t12 + v0&i32(-16) | v0&i32(15)
		store32(m.memory[uint32(t11):], uint32(v2))
	}
l0:
	store32(m.memory[uint32(v1):], uint32(v2|i32(1)))
	v0 = v2 & i32(-16)
	store32(m.memory[uint32(v0+v1-i32(4)):], uint32(v0))
	t13 := int32(load32(m.memory[uint32(v3):]))
	store32(m.memory[uint32(v3):], uint32(t13|i32(2)))
	t14 := int32(load32(m.memory[uint32(v1):]))
	m._tlsf_mapping(t14&i32(-16), i32(1), v4+i32(12), v4+i32(8))
	t15 := int32(load32(m.memory[int64(uint32(v4))+12:]))
	v2 = t15
	t16 := int32(load32(m.memory[int64(uint32(v4))+8:]))
	t17 := v2 << 6
	v3 = t16
	v5 = t17 + v3<<2 + i32(65640)
	t18 := int32(load32(m.memory[uint32(v5):]))
	v0 = t18
	store32(m.memory[int64(uint32(v1))+8:], uint32(i32(0)))
	store32(m.memory[int64(uint32(v1))+4:], uint32(v0))
	store32(m.memory[uint32(v5):], uint32(v1))
	if v0 != 0 {
		store32(m.memory[int64(uint32(v0))+8:], uint32(v1))
	}
	t19 := int32(load32(m.memory[uint32(i32(65536)):]))
	store32(m.memory[uint32(i32(65536)):], uint32(t19|i32_shl(i32(1), v2)))
	v0 = v2<<2 + i32(65540)
	t20 := int32(load32(m.memory[uint32(v0):]))
	store32(m.memory[uint32(v0):], uint32(t20|i32_shl(i32(1), v3)))
	m.___stack_pointer = v4 + i32(16)
}
func (m *Module) _tlsf_remove_free_block(v0 int32) {
	var v1, v2, v3 int32
	t0 := m.___stack_pointer
	v2 = t0 - i32(16)
	m.___stack_pointer = v2
	t1 := int32(load32(m.memory[uint32(v0):]))
	m._tlsf_mapping(t1&i32(-16), i32(1), v2+i32(12), v2+i32(8))
	t2 := int32(load32(m.memory[int64(uint32(v0))+8:]))
	v1 = t2
	t3 := int32(load32(m.memory[int64(uint32(v0))+4:]))
	v0 = t3
	if v0 != 0 {
		store32(m.memory[int64(uint32(v0))+8:], uint32(v1))
	}
	{
		if v1 != 0 {
			store32(m.memory[int64(uint32(v1))+4:], uint32(v0))
			goto l0
		}
		t4 := int32(load32(m.memory[int64(uint32(v2))+12:]))
		v3 = t4
		t5 := int32(load32(m.memory[int64(uint32(v2))+8:]))
		t6 := v3 << 6
		v1 = t5
		store32(m.memory[uint32(t6+v1<<2+i32(65640)):], uint32(v0))
		if v0 != 0 {
			goto l0
		}
		v0 = v3<<2 + i32(65540)
		t7 := int32(load32(m.memory[uint32(v0):]))
		v1 = t7 & i32_rotl(i32(-2), v1)
		store32(m.memory[uint32(v0):], uint32(v1))
		if v1 != 0 {
			goto l0
		}
		t8 := int32(load32(m.memory[uint32(i32(65536)):]))
		store32(m.memory[uint32(i32(65536)):], uint32(t8&i32_rotl(i32(-2), v3)))
	}
l0:
	m.___stack_pointer = v2 + i32(16)
}
func (m *Module) Xmalloc(v0 int32) int32 {
	var v1, v2, v3, v4 int32
	{
		if v0 <= i32(0) {
			goto l0
		}
		{
			v4 = (v0 + i32(19)) & i32(-16)
			t0 := m._tlsf_find_free_block(v4)
			v1 = t0
			if v1 != 0 {
				goto l1
			}
			v3 = int32(uint32(v0+i32(65571)) >> 16)
			t1 := int32(memory_grow(&m.memory, int64(v3), m.maxMem))
			v0 = t1
			if v0 == i32(-1) {
				goto l0
			}
			v2 = v0 << 16
			t2 := int32(load32(m.memory[uint32(i32(67240)):]))
			var p3 int32
			if v2 == t2 {
				p3 = 1
			}
			v1 = p3
			v3 = (v0 + v3) << 16
			t5 := v3
			p4 := i32(12)
			if v1 != 0 {
				p4 = i32(-4)
			}
			v0 = p4 + v2
			if t5-v0 >= i32(20) {
				v2 = v3 - i32(4)
				store32(m.memory[uint32(v2):], uint32(i32(0)))
				t7 := v0
				var p6 int32
				if v1 != 0 {
					t8 := int32(load32(m.memory[uint32(v0):]))
					p6 = t8 & i32(15)
				} else {
					p6 = i32(0)
				}
				store32(m.memory[uint32(t7):], uint32(p6|(v2-v0)))
				m._tlsf_block_free(v0)
				store32(m.memory[uint32(i32(67240)):], uint32(v3))
			}
			t9 := m._tlsf_find_free_block(v4)
			v1 = t9
			if v1 != 0 {
				goto l1
			}
			return i32(0)
		}
	l1:
		m._tlsf_remove_free_block(v1)
		t10 := int32(load32(m.memory[uint32(v1):]))
		t11 := v1
		v0 = t10
		store32(m.memory[uint32(t11):], uint32(v0&i32(-2)))
		v0 = v1 + v0&i32(-16)
		t12 := int32(load32(m.memory[uint32(v0):]))
		store32(m.memory[uint32(v0):], uint32(t12&i32(-3)))
		t13 := m._tlsf_block_split(v1, v4)
		v0 = t13
		if v0 != 0 {
			m._tlsf_block_free(v0)
		}
		v2 = v1 + i32(4)
	}
l0:
	return v2
}
func (m *Module) _tlsf_find_free_block(v0 int32) int32 {
	var v1, v2, v3 int32
	t0 := m.___stack_pointer
	v1 = t0 - i32(16)
	m.___stack_pointer = v1
	m._tlsf_mapping(v0, i32(0), v1+i32(12), v1+i32(8))
	{
		t1 := int32(load32(m.memory[int64(uint32(v1))+12:]))
		v2 = t1
		t2 := int32(load32(m.memory[uint32(v2<<2+i32(65540)):]))
		t3 := int32(load32(m.memory[int64(uint32(v1))+8:]))
		v0 = t2 & i32_shl(i32(-1), t3)
		if v0 == 0 {
			t4 := int32(load32(m.memory[uint32(i32(65536)):]))
			v0 = t4 & i32_shl(i32(-1), v2+i32(1))
			if v0 == 0 {
				goto l0
			}
			v2 = int32(bits.TrailingZeros32(uint32(v0)))
			t5 := int32(load32(m.memory[int64(uint32(v2<<2))+65540:]))
			v0 = t5
		}
		t7 := v2 << 6
		p6 := i32(-1)
		if v0 != 0 {
			p6 = int32(bits.TrailingZeros32(uint32(v0)))
		}
		t8 := int32(load32(m.memory[uint32(t7+p6<<2+i32(65640)):]))
		v3 = t8
	}
l0:
	m.___stack_pointer = v1 + i32(16)
	return v3
}
func (m *Module) _tlsf_block_split(v0, v1 int32) int32 {
	var v2, v3, v4 int32
	t0 := int32(load32(m.memory[uint32(v0):]))
	v2 = t0
	v3 = v2&i32(-16) - v1
	if uint32(v3) >= uint32(i32(16)) {
		store32(m.memory[uint32(v0):], uint32(v2&i32(15)|v1))
		v4 = v0 + v1&i32(-16)
		store32(m.memory[uint32(v4):], uint32(v3))
	}
	return v4
}
func (m *Module) _tlsf_mapping(v0, v1, v2, v3 int32) {
	var v4, v5, v6 int32
	if uint32(v0) <= uint32(i32(255)) {
		store32(m.memory[uint32(v2):], uint32(i32(0)))
		store32(m.memory[uint32(v3):], uint32(int32(uint32(v0)>>4)))
		return
	}
	t0 := v2
	v4 = int32(bits.LeadingZeros32(uint32(v0)))
	store32(m.memory[uint32(t0):], uint32(i32(24)-v4))
	t1 := v3
	t2 := v0
	v5 = i32(27) - v4
	v6 = i32_shr_u(t2, v5) & i32(15)
	store32(m.memory[uint32(t1):], uint32(v6))
	{
		if v1 != 0 {
			return
		}
		if int64(uint32(v0))&(i64_shl(i64(-1), int64(uint32(v5)))^i64(-1)) == 0 {
			return
		}
		t3 := v3
		v0 = v6 + i32(1)
		store32(m.memory[uint32(t3):], uint32(v0))
		if v0 != i32(16) {
			return
		}
		store32(m.memory[uint32(v3):], uint32(i32(0)))
		store32(m.memory[uint32(v2):], uint32(i32(25)-v4))
	}
}
func (m *Module) Xrealloc(v0, v1 int32) int32 {
	var v2, v3, v4, v5, v6, v7 int32
	if v1 == 0 {
		m.Xfree(v0)
		return i32(0)
	}
	{
		if v1 < i32(0) {
			goto l0
		}
		if v0 == 0 {
			t0 := m.Xmalloc(v1)
			return t0
		}
		if v0&i32(15) != 0 {
			goto l1
		}
		v2 = v0 - i32(4)
		t1 := int32(load32(m.memory[uint32(v2):]))
		v3 = t1
		if v3&i32(1) != 0 {
			goto l1
		}
		v4 = (v1 + i32(19)) & i32(-16)
		t2 := v4
		v3 = v3 & i32(-16)
		if uint32(t2) <= uint32(v3) {
			t3 := m._tlsf_block_split(v2, v4)
			v1 = t3
			if v1 == 0 {
				goto l2
			}
			m._tlsf_block_free(v1)
			goto l2
		}
		{
			v6 = v2 + v3
			t4 := int32(load32(m.memory[uint32(v6):]))
			v7 = t4
			if v7&i32(1) == 0 {
				goto l3
			}
			if uint32(v7&i32(-16)+v3) < uint32(v4) {
				goto l3
			}
			m._tlsf_remove_free_block(v6)
			t5 := int32(load32(m.memory[uint32(v6):]))
			t6 := v2
			v1 = t5&i32(-16) + v3
			t7 := int32(load32(m.memory[uint32(v2):]))
			store32(m.memory[uint32(t6):], uint32(v1|t7&i32(15)))
			v1 = v1 + v2
			t8 := int32(load32(m.memory[uint32(v1):]))
			store32(m.memory[uint32(v1):], uint32(t8&i32(-3)))
			t9 := m._tlsf_block_split(v2, v4)
			v1 = t9
			if v1 == 0 {
				goto l2
			}
			m._tlsf_block_free(v1)
			goto l2
		}
	l3:
		t10 := m.Xmalloc(v1)
		v1 = t10
		if v1 == 0 {
			goto l0
		}
		v5 = v3 - i32(4)
		if v5 != 0 {
			memory_copy(m.memory, uint32(v1), uint32(v0), uint32(v5))
		}
		m.Xfree(v0)
		v5 = v1
	}
l0:
	return v5
l1:
	panic("unreachable")
l2:
	return v0
}
func (m *Module) Xmemalign(v0, v1 int32) int32 {
	var v2, v3, v4 int32
	{
		if v1 <= i32(0) {
			goto l0
		}
		if int32(bits.OnesCount32(uint32(v0))) != i32(1) {
			goto l0
		}
		if uint32(v0) <= uint32(i32(16)) {
			t0 := m.Xmalloc(v1)
			return t0
		}
		t1 := m.Xmalloc(v0 + v1)
		v2 = t1
		if v2 == 0 {
			goto l0
		}
		if v2&i32(15) != 0 {
			goto l1
		}
		v3 = v2 - i32(4)
		t2 := int32(load32(m.memory[uint32(v3):]))
		if t2&i32(1) != 0 {
			goto l1
		}
		{
			v4 = (v0 + v2 - i32(1)) & (i32(0) - v0)
			t4 := v4
			p3 := i32(0)
			if v4-v2 < i32(16) {
				p3 = v0
			}
			p5 := i32(0)
			if uint32(v2) < uint32(v4) {
				p5 = p3
			}
			v0 = t4 + p5
			if uint32(v0) <= uint32(v2) {
				v0 = v3
				goto l2
			}
			t6 := m._tlsf_block_split(v3, v0-v2)
			v0 = t6
			m._tlsf_block_free(v3)
		}
	l2:
		t7 := m._tlsf_block_split(v0, (v1+i32(19))&i32(-16))
		v1 = t7
		if v1 != 0 {
			m._tlsf_block_free(v1)
		}
		v3 = v0 + i32(4)
	}
l0:
	return v3
l1:
	panic("unreachable")
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32(b []byte) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(b)
	}
	v := *(*uint32)(unsafe.Pointer((*[4]byte)(b)))
	if big {
		return bits.ReverseBytes32(v)
	}
	return v
}

//go:nosplit
func store32(b []byte, v uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(b, v)
		return
	}
	if big {
		v = bits.ReverseBytes32(v)
	}
	*(*uint32)(unsafe.Pointer((*[4]byte)(b))) = v
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i64_shl(x, y int64) int64 {
	return x << (y & 63)
}

//go:nosplit
func i32_rotl(x, y int32) int32 {
	return int32(bits.RotateLeft32(uint32(x), int(y)))
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := int64(len(buf))
	old := len >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := new<<16 - len
	max = min(max, int64(math.MaxInt)>>16)
	if new > max || new < old || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], mem[z:w])
}
