// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	_ "embed"
	"testing"

	"github.com/ncruces/wasm2go/spectest"
)

//go:embed table_get64.json
var data []byte

func Test(t *testing.T) {
	spectest.Test(t, New(), data, "table_get64.0.wasm")
}
