// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	t1       []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 2)
	m.t1 = make([]any, 3)
	m.elements = [][]any{{m.f0}}
	copy(m.t1[1:], m.elements[0])
	return m
}
func (m *Module) f0() {
}
func (m *Module) Xinit(v0 any) {
	t0 := v0
	m.t0[int64(1)] = t0
	t1 := m.t1[int64(1)]
	m.t1[int64(2)] = t1
}
func (m *Module) Xget_externref(v0 int64) any {
	t0 := v0
	t1 := m.t0[t0]
	return t1
}
func (m *Module) Xget_funcref(v0 int64) any {
	t0 := v0
	t1 := m.t1[t0]
	return t1
}
func (m *Module) Xis_null_funcref(v0 int64) int32 {
	t0 := v0
	t1 := m.Xget_funcref(t0)
	var p2 int32
	if t1 == nil {
		p2 = 1
	}
	return p2
}
