// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xno_dce_i32_div_s(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	t2 := i32_div_s(t0, t1)
	_ = t2
}
func (m *Module) Xno_dce_i32_div_u(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	t2 := int32(uint32(t0) / uint32(t1))
	_ = t2
}
func (m *Module) Xno_dce_i64_div_s(v0 int64, v1 int64) {
	t0 := v0
	t1 := v1
	t2 := i64_div_s(t0, t1)
	_ = t2
}
func (m *Module) Xno_dce_i64_div_u(v0 int64, v1 int64) {
	t0 := v0
	t1 := v1
	t2 := int64(uint64(t0) / uint64(t1))
	_ = t2
}

func i32_div_s(x, y int32) int32 {
	if x == math.MinInt32 && y == -1 {
		panic("integer overflow")
	}
	return x / y
}

func i64_div_s(x, y int64) int64 {
	if x == math.MinInt64 && y == -1 {
		panic("integer overflow")
	}
	return x / y
}
