// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 1
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	return m
}
func (m *Module) Xf32응2Esimple_x4_sum(v0 int32, v1 int32, v2 int32) {
	var v3, v4, v5, v6, v7, v8, v9, v10 float32
	_, _, _, _, _, _, _, _ = v3, v4, v5, v6, v7, v8, v9, v10
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	v3 = t0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))
	v4 = t1
	t2 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
	v5 = t2
	t3 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+12:]))
	v6 = t3
	t4 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(v1):]))
	v7 = t4
	t5 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+4:]))
	v8 = t5
	t6 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+8:]))
	v9 = t6
	t7 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+12:]))
	v10 = t7
	binary.LittleEndian.PutUint32(m.memory[uint32(v2):], math.Float32bits(float32(v3+v7)))
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+4:], math.Float32bits(float32(v4+v8)))
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+8:], math.Float32bits(float32(v5+v9)))
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+12:], math.Float32bits(float32(v6+v10)))
}
func (m *Module) Xf32응2Eload(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}

const data0 = "\x01\x00\x00\x00\x01\x00\x00\x80\x01\x00\x00\x00\x01\x00\x00\x80\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
