// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 281474976710656
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) Xfill(v0 int64, v1 int32, v2 int64) {
	t0 := v0
	t1 := v1
	t2 := v2
	memory64_fill(m.memory, t0, t1, t2)
}
func (m *Module) Xload8_u(v0 int64) int32 {
	t0 := v0
	t1 := int32(m.memory[t0])
	return t1
}

func memory64_fill(mem []byte, dest int64, val int32, n int64) {
	x := uint64(dest)
	y := x + uint64(n)
	buf := mem[x:y]
	if len(buf) > 0 {
		buf[0] = byte(val)
		for i := 1; i < len(buf); {
			chunk := min(i, 8192)
			i += copy(buf[i:], buf[:chunk])
		}
	}
}
