// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_add_neg(v0 float32) float32 {
	return float32(-v0 + v0)
}
func (m *Module) Xf64_no_fold_add_neg(v0 float64) float64 {
	return float64(-v0 + v0)
}
