package main

import (
	"bytes"
	"embed"
	"flag"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/ncruces/wasm2go/util"
)

//go:embed go/*.go c/*.c c/*.h
var src embed.FS

var (
	output = flag.String("o", "", "output file (default stdout)")
	pkg    = flag.String("pkg", "main", "package name")
	m64    = flag.Bool("m64", false, "use 64-bit pointers (int64)")
	deref  = flag.Bool("deref-mem", false, "dereference memory (*m.memory instead of m.memory)")
	cout   = flag.String("c-out", "", "extract libc C source and header files to directory")
)

func main() {
	flag.Parse()

	if *cout != "" {
		s, err := fs.Sub(src, "c")
		if err != nil {
			log.Fatal(err)
		}
		err = os.RemoveAll(*cout)
		if err != nil {
			log.Fatal(err)
		}
		err = os.CopyFS(*cout, s)
		if err != nil {
			log.Fatal(err)
		}
	}

	funcs := flag.Args()
	if len(funcs) == 0 {
		return
	}

	ptrType := "int32"
	uptrType := "uint32"
	if *m64 {
		ptrType = "int64"
		uptrType = "uint64"
	}

	fset := token.NewFileSet()
	entries, err := src.ReadDir("go")
	if err != nil {
		log.Fatal(err)
	}

	allImports := make(map[string]string)
	available := make(map[string]*ast.FuncDecl)

	// Map out the functions and track module paths for automatic import resolution
	for _, entry := range entries {
		if entry.Name() == "libc.go" {
			continue
		}
		data, err := src.ReadFile("go/" + entry.Name())
		if err != nil {
			log.Fatal(err)
		}
		f, err := parser.ParseFile(fset, entry.Name(), data, 0)
		if err != nil {
			log.Fatal(err)
		}

		for _, imp := range f.Imports {
			path := strings.Trim(imp.Path.Value, `"`)
			name := path
			if idx := strings.LastIndex(name, "/"); idx >= 0 {
				name = name[idx+1:]
			}
			if imp.Name != nil {
				name = imp.Name.Name
			}
			allImports[name] = path
		}

		for _, decl := range f.Decls {
			if fd, ok := decl.(*ast.FuncDecl); ok {
				available[fd.Name.Name] = fd
			}
		}
	}

	queue := append([]string(nil), funcs...)
	visited := make(map[string]bool)
	var keep []*ast.FuncDecl

	// Tree-shake the AST
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]

		if visited[name] {
			continue
		}
		visited[name] = true

		fd, ok := available[name]
		if !ok {
			log.Fatalf("function %s not found in templates", name)
		}
		keep = append(keep, fd)

		// Search for other internal dependencies inside this one's scope
		ast.Inspect(fd.Body, func(n ast.Node) bool {
			if call, ok := n.(*ast.CallExpr); ok {
				if id, ok := call.Fun.(*ast.Ident); ok {
					if _, exists := available[id.Name]; exists {
						queue = append(queue, id.Name)
					}
				}
			}
			return true
		})
	}

	usedImports := make(set[string])

	// Execute the rewriting permutations
	for _, fd := range keep {
		fd.Recv = &ast.FieldList{
			List: []*ast.Field{{
				Names: []*ast.Ident{ast.NewIdent("m")},
				Type:  &ast.StarExpr{X: ast.NewIdent("Module")},
			}},
		}

		ast.Inspect(fd, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.SliceExpr:
				if id, ok := x.X.(*ast.Ident); ok && id.Name == "memory" {
					x.X = makeMemoryExpr(*deref)
				}
			case *ast.IndexExpr:
				if id, ok := x.X.(*ast.Ident); ok && id.Name == "memory" {
					x.X = makeMemoryExpr(*deref)
				}
			case *ast.CallExpr:
				if id, ok := x.Fun.(*ast.Ident); ok && available[id.Name] != nil {
					x.Fun = &ast.SelectorExpr{X: ast.NewIdent("m"), Sel: util.MangleID(id.Name, util.IDInternal)}
				}
				for i, arg := range x.Args {
					if id, ok := arg.(*ast.Ident); ok && id.Name == "memory" {
						x.Args[i] = makeMemoryExpr(*deref)
					}
				}
			case *ast.Ident:
				switch x.Name {
				case "ptr":
					x.Name = ptrType
				case "uptr":
					x.Name = uptrType
				}
			case *ast.SelectorExpr:
				if id, ok := x.X.(*ast.Ident); ok {
					if path, exists := allImports[id.Name]; exists {
						usedImports.add(path)
					}
				}
			}
			return true
		})

		// Finally mangle the function's own name
		fd.Name = util.MangleID(fd.Name.Name, util.IDInternal)
	}

	// Write the unified file
	outAST := &ast.File{
		Name: ast.NewIdent(*pkg),
	}

	if len(usedImports) > 0 {
		var specs []ast.Spec
		for _, imp := range slices.Sorted(maps.Keys(usedImports)) {
			specs = append(specs, &ast.ImportSpec{
				Path: &ast.BasicLit{Kind: token.STRING, Value: `"` + imp + `"`},
			})
		}
		outAST.Decls = append(outAST.Decls, &ast.GenDecl{Tok: token.IMPORT, Specs: specs})
	}

	for _, fd := range keep {
		outAST.Decls = append(outAST.Decls, fd)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by libc-gen. DO NOT EDIT.\n\n")
	if err := format.Node(&buf, fset, outAST); err != nil {
		log.Fatal(err)
	}

	outData := buf.Bytes()
	if *output == "" {
		os.Stdout.Write(outData)
	} else {
		if err := os.WriteFile(*output, outData, 0644); err != nil {
			log.Fatal(err)
		}
	}
}

func makeMemoryExpr(deref bool) ast.Expr {
	sel := &ast.SelectorExpr{X: ast.NewIdent("m"), Sel: ast.NewIdent("memory")}
	if deref {
		return &ast.ParenExpr{X: &ast.StarExpr{X: sel}}
	}
	return sel
}
