// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_distribute_exact(v0 float32) float32 {
	t0 := v0
	t1 := float32(float32(-8) * t0)
	t2 := v0
	t3 := float32(float32(8) * t2)
	t4 := float32(t1 + t3)
	return t4
}
func (m *Module) Xf64_no_distribute_exact(v0 float64) float64 {
	t0 := v0
	t1 := float64(float64(-8) * t0)
	t2 := v0
	t3 := float64(float64(8) * t2)
	t4 := float64(t1 + t3)
	return t4
}
