// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xno_dce_i32_trunc_f32_s_1vb1bz5(v0 float32) {
	t0 := i32_trunc_f32_s(v0)
	_ = t0
}
func (m *Module) Xno_dce_i32_trunc_f32_u_1mvkemh(v0 float32) {
	t0 := i32_trunc_f32_u(v0)
	_ = t0
}
func (m *Module) Xno_dce_i32_trunc_f64_s_10z7tml(v0 float64) {
	t0 := i32_trunc_f64_s(v0)
	_ = t0
}
func (m *Module) Xno_dce_i32_trunc_f64_u_19h2g5x(v0 float64) {
	t0 := i32_trunc_f64_u(v0)
	_ = t0
}
func (m *Module) Xno_dce_i64_trunc_f32_s_mmfswg(v0 float32) {
	t0 := i64_trunc_f32_s(v0)
	_ = t0
}
func (m *Module) Xno_dce_i64_trunc_f32_u_x28z5k(v0 float32) {
	t0 := i64_trunc_f32_u(v0)
	_ = t0
}
func (m *Module) Xno_dce_i64_trunc_f64_s_anadsc(v0 float64) {
	t0 := i64_trunc_f64_s(v0)
	_ = t0
}
func (m *Module) Xno_dce_i64_trunc_f64_u_9xoro(v0 float64) {
	t0 := i64_trunc_f64_u(v0)
	_ = t0
}

func i32_trunc_f64_s(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(x)
}

func i32_trunc_f32_s(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(x)
}

func i32_trunc_f64_u(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(uint32(x))
}

func i32_trunc_f32_u(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(uint32(x))
}

func i64_trunc_f64_s(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(x)
}

func i64_trunc_f32_s(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(x)
}

func i64_trunc_f64_u(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(uint64(x))
}

func i64_trunc_f32_u(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(uint64(x))
}
