package main

import (
	"bufio"
	"encoding/binary"
	"errors"
	"go/ast"
	"go/printer"
	"go/token"
	"io"
	"log"
	"os"
)

var generated ast.File

func main() {
	r := bufio.NewReader(os.Stdin)

	err := readHeader(r)
	if err != nil {
		log.Fatal(err)
	}

	generated.Name = ast.NewIdent(os.Args[1])

	for {
		id, err := peekSectionID(r)
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		if id == sectionCode {
			break
		}
		if err := skipSection(r, id); err != nil {
			log.Fatal(err)
		}
	}

	generated.Decls = append(generated.Decls, createModuleStruct())

	os.Stdout.WriteString("// Code generated by wasm2go. DO NOT EDIT.\n\n")
	err = printer.Fprint(os.Stdout, token.NewFileSet(), &generated)
	if err != nil {
		log.Fatal(err)
	}
}

func readHeader(r io.Reader) error {
	var header [8]byte
	if _, err := io.ReadFull(r, header[:]); err != nil {
		return err
	}
	if string(header[:4]) != "\x00asm" {
		return errors.New("invalid magic number")
	}
	if binary.LittleEndian.Uint32(header[4:]) != 1 {
		return errors.New("invalid version")
	}
	return nil
}

func createModuleStruct() ast.Decl {
	return &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: ast.NewIdent("Module"),
				Type: &ast.StructType{
					Fields: &ast.FieldList{
						List: []*ast.Field{
							{
								Names: []*ast.Ident{ast.NewIdent("memory")},
								Type: &ast.ArrayType{
									Elt: ast.NewIdent("byte"),
								},
							},
						},
					},
				},
			},
		},
	}
}
