package main

import (
	"bytes"
	"errors"
	"go/format"
	"html/template"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

//go:generate go test -tags generator -run translate -args -unsafe
//go:generate go test -tags generator -run translate

func Test_translate(t *testing.T) {
	tests := []string{
		"fib", "loops", "memory", "primes", "recursion", "stack", "table", "trig",
		"regression/select_effect", "regression/store_grow", "regression/tee_self_loop",
	}
	for _, name := range tests {
		t.Run(name, func(t *testing.T) {
			path := "testdata/" + name + "/" + filepath.Base(name)

			in, err := os.Open(path + ".wasm")
			if err != nil {
				t.Fatal(err)
			}
			defer in.Close()

			var out bytes.Buffer
			err = translate(in, &out)
			if err != nil {
				t.Fatal(err)
			}

			err = os.WriteFile(path+".go", out.Bytes(), 0644)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}

func Test_translateSpecTest(t *testing.T) {
	*nanbox = true
	t.Cleanup(func() { *nanbox = false })
	slices.Sort(specHostModules)

	filepath.WalkDir("internal/spectest/", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if !*unsafe && strings.HasSuffix(path, "/threads") {
				return filepath.SkipDir
			}
			if strings.HasSuffix(path, "skip") {
				return filepath.SkipDir
			}
			return nil
		}
		if ext := filepath.Ext(path); ext == ".wasm" {
			in, err := os.Open(path)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}
			defer in.Close()

			var out bytes.Buffer
			err = translate(in, &out)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}

			err = os.WriteFile(strings.TrimRight(path, ext)+".go", out.Bytes(), 0644)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}

			err = generateSpecTest(path)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}
		}
		return nil
	})
}

func generateSpecTest(path string) error {
	dir := filepath.Dir(path)
	baseDir := filepath.Base(dir)
	wasmFile := filepath.Base(path)
	jsonFile := baseDir + ".json"
	testFile := filepath.Join(dir, "gen_test.go")

	if _, err := os.Stat(filepath.Join(dir, baseDir+".json")); errors.Is(err, fs.ErrNotExist) {
		return nil
	}

	type specFileInfo struct {
		JSONFile   string
		WasmFile   string
		HostModule string
	}

	info := specFileInfo{
		JSONFile: jsonFile,
		WasmFile: wasmFile,
	}

	if _, found := slices.BinarySearch(specHostModules, baseDir); found {
		info.HostModule = `spectest.Host{T: t}`
	}

	tmpl, err := template.New("spectest").Parse(specTestTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, info); err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(testFile, src, 0644)
}

const specTestTemplate = `// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	_ "embed"
	"testing"

	"github.com/ncruces/wasm2go/internal/spectest"
)

//go:embed {{.JSONFile}}
var data []byte

func Test(t *testing.T) {
	spectest.Test(t, New({{.HostModule}}), data, "{{.WasmFile}}")
}
`

var specHostModules = []string{
	"data.3",
	"elem.58",
	"func_ptrs.0",
	"global.0",
	"global.23",
	"linking.2",
	"names.3",
	"return_call.0",
	"return_call_indirect.0",
	"start.5",
	"start.6",
	"start.7",
}
