// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 0)
	return m
}
func (m *Module) Xload_at_zero() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	return t0
}
func (m *Module) Xstore_at_zero() {
	binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(2)))
}
func (m *Module) Xload_at_page_size() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(65536)):]))
	return t0
}
func (m *Module) Xstore_at_page_size() {
	binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(65536)):], uint32(int32(3)))
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}
func (m *Module) Xsize() int32 {
	t0 := int32(len(m.memory) >> 16)
	return t0
}

//go:nosplit
func i32_const(x int32) int32 { return x }

func memory_grow(mem *[]byte, delta, max int32) int32 {
	buf := *mem
	len := len(buf)
	old := int32(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
