// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32응2Enot_lt(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32응2Enot_le(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32응2Enot_gt(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32응2Enot_ge(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64응2Enot_lt(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64응2Enot_le(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64응2Enot_gt(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64응2Enot_ge(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
