// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_not_lt_1o38sw4(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32_not_le_g9rz1k(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32_not_gt_vgl5r9(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf32_not_ge_14vrj0p(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64_not_lt_i1i0bg(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64_not_le_19a2agg(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64_not_gt_1sn04zh(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xf64_not_ge_2zj0i9(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
