// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math/bits"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	g0       int32
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.f14}}
	copy(m.t0[0:], m.elements[0])
	m.g0 = i32_const(0)
	return m
}
func (m *Module) Xas_br_value_1sx9dl7() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_cond_p6cjb3() {
	{
		t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		if t0 != 0 {
			goto l0
		}
	}
l0:
}
func (m *Module) Xas_br_if_value_1tlgvkk() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		if int32(1) != 0 {
			p0 = t1
			goto l0
		}
		_ = t1
		p0 = int32(7)
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_value_cond_pzz0yu() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		if t1 != 0 {
			p0 = int32(6)
			goto l0
		}
		_ = int32(6)
		p0 = int32(7)
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_index_sdkzon() {
	{
		t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		switch t0 {
		default:
			goto l0
		}
	}
l0:
}
func (m *Module) Xas_br_table_value_1ic2jxx() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		switch int32(1) {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_value_index_fupi8r() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		switch t1 {
		default:
			p0 = int32(6)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas_return_value_1wph1uy() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	return t0
}
func (m *Module) Xas_if_cond_ok3ah4() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	var p1 int32
	_ = p1
	if t0 != 0 {
		p1 = i32_const(0)
	} else {
		p1 = int32(1)
	}
	return p1
}
func (m *Module) Xas_if_then_8by7gv() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		p0 = t1
	} else {
		p0 = i32_const(0)
	}
	return p0
}
func (m *Module) Xas_if_else_y9fza0() int32 {
	var p0 int32
	_ = p0
	if i32_const(0) != 0 {
		p0 = i32_const(0)
	} else {
		t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas_select_first_1p4pbiq(v0 int32, v1 int32) int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	p1 := v0
	if v1 != 0 {
		p1 = t0
	}
	return p1
}
func (m *Module) Xas_select_second_og5yck(v0 int32, v1 int32) int32 {
	t1 := v0
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	p2 := t0
	if v1 != 0 {
		p2 = t1
	}
	return p2
}
func (m *Module) Xas_select_cond_1gi9cp1() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	p1 := int32(1)
	if t0 != 0 {
		p1 = i32_const(0)
	}
	return p1
}
func (m *Module) f14(v0 int32, v1 int32, v2 int32) int32 {
	return i32_const(-1)
}
func (m *Module) Xas_call_first_oczht1() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.f14(t0, int32(2), int32(3))
	return t1
}
func (m *Module) Xas_call_mid_1hypaa8() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.f14(int32(1), t0, int32(3))
	return t1
}
func (m *Module) Xas_call_last_5v6w73() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.f14(int32(1), int32(2), t0)
	return t1
}
func (m *Module) Xas_call_indirect_first_1kls7bs() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32, v2 int32) int32)(t0, int32(2), int32(3))
	return t1
}
func (m *Module) Xas_call_indirect_mid_1u5vulp() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32, v2 int32) int32)(int32(1), t0, int32(3))
	return t1
}
func (m *Module) Xas_call_indirect_last_os2e8m() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32, v2 int32) int32)(int32(1), int32(2), t0)
	return t1
}
func (m *Module) Xas_call_indirect_index_mucjd() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := m.t0[uint(t0)].(func(v0 int32, v1 int32, v2 int32) int32)(int32(1), int32(2), int32(3))
	return t1
}
func (m *Module) Xas_local_set_value_1e0q6mz() {
	var v0 int32
	_ = v0
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	v0 = t0
}
func (m *Module) Xas_local_tee_value_11lf5v3() int32 {
	var v0 int32
	_ = v0
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	v0 = t0
	return v0
}
func (m *Module) Xas_global_set_value_p447yq() {
	var v0 int32
	_ = v0
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	m.g0 = t0
}
func (m *Module) Xas_load_address_1s1elxs() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xas_loadN_address_xz9je7() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	t1 := int32(int8(m.memory[uint32(t0)]))
	return t1
}
func (m *Module) Xas_store_address_374rd1() {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(int32(7)))
}
func (m *Module) Xas_store_value_1bx4mta() {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(2)):], uint32(t0))
}
func (m *Module) Xas_storeN_address_qez1rh() {
	t0 := int32(int8(m.memory[uint32(i32_const(0))]))
	m.memory[uint32(t0)] = byte(int32(7))
}
func (m *Module) Xas_storeN_value_7lcb3d() {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32_const(0)):]))
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(2)):], uint16(t0))
}
func (m *Module) Xas_unary_operand_kr3bi8() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	return int32(bits.LeadingZeros32(uint32(t0)))
}
func (m *Module) Xas_binary_left_mz7no() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	return t0 + int32(10)
}
func (m *Module) Xas_binary_right_1h2yoyv() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	return int32(10) - t0
}
func (m *Module) Xas_test_operand_khoiq6() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	var p1 int32
	if t0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas_compare_left_afzngt() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	var p1 int32
	if t0 <= int32(10) {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas_compare_right_1jgames() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	var p1 int32
	if int32(10) != t0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas_memory_grow_size_7te2ha() int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(100)):]))
	t1 := int32(memory_grow(&m.memory, int64(t0), m.maxMem))
	return t1
}

//go:nosplit
func i32_const(x int32) int32 { return x }

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
