// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	tags []*byte
}

func New() *Module {
	m := &Module{}
	m.tags = make([]*byte, 6)
	m.tags[0] = new(byte)
	m.tags[1] = new(byte)
	m.tags[2] = new(byte)
	m.tags[3] = new(byte)
	m.tags[4] = new(byte)
	m.tags[5] = new(byte)
	return m
}
func (m *Module) Xthrow_if(v0 int32) int32 {
	t0 := v0
	if t0 != i32_const(0) {
		panic(&Exception{Tag: m.tags[0], Val: []any{}})
	}
	return i32_const(0)
}
func (m *Module) Xthrow_param_f32(v0 float32) {
	t0 := v0
	panic(&Exception{Tag: m.tags[2], Val: []any{t0}})
}
func (m *Module) Xthrow_param_i64(v0 int64) {
	t0 := v0
	panic(&Exception{Tag: m.tags[3], Val: []any{t0}})
}
func (m *Module) Xthrow_param_f64(v0 float64) {
	t0 := v0
	panic(&Exception{Tag: m.tags[4], Val: []any{t0}})
}
func (m *Module) Xthrow_polymorphic() {
	panic(&Exception{Tag: m.tags[0], Val: []any{}})
}
func (m *Module) Xthrow_polymorphic_block() {
	var p0 int32
	_ = p0
	{
		panic(&Exception{Tag: m.tags[0], Val: []any{}})
	}
}
func (m *Module) f6() {
	panic(&Exception{Tag: m.tags[5], Val: []any{int32(1), int32(2)}})
}
func (m *Module) Xtest_throw_1_2() {
	if jump, caught := func() (jumpID int, caught *Exception) {
		defer func() {
			r := recover()
			if r == nil {
				return
			}
			if ex, ok := r.(*Exception); ok {
				if ex.Tag == m.tags[5] {
					jumpID = 0
					caught = ex
					return
				}
			}
			panic(r)
		}()
		m.f6()
		return 0, nil
	}(); jump != 0 {
		switch jump {
		case -1:
			return
		default:
			panic("unreachable")
		}
	} else if caught != nil {
		switch caught.Tag {
		case m.tags[5]:
			{
				t0 := caught.Val[0].(int32)
				t1 := caught.Val[1].(int32)
				if t1 != int32(2) {
					panic("unreachable")
				}
				if t0 != int32(1) {
					panic("unreachable")
				}
			}
		}
	}
}

type Exception = struct {
	Tag *byte
	Val []any
}

//go:nosplit
func i32_const(x int32) int32 { return x }
