// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 10
	m.memory = make([]byte, 0)
	return m
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}

func memory_grow[T int | int32 | int64](mem *[]byte, delta, max T) T {
	buf := *mem
	len := len(buf)
	old := T(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
