// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	g0 any
	g1 any
}

func New() *Module {
	m := &Module{}
	m.g0 = nil
	m.g1 = nil
	return m
}
func (m *Module) Xexternref() any {
	return nil
}
func (m *Module) Xfuncref() any {
	return nil
}
