// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_sub1_mul_add(v0 float32, v1 float32) float32 {
	return float32(float32(float32(v0-f32_const(1))*v1) + v1)
}
func (m *Module) Xf64_no_fold_sub1_mul_add(v0 float64, v1 float64) float64 {
	return float64(float64(float64(v0-f64_const(1))*v1) + v1)
}

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
