// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_no_fold_shr_s_shl_1qs00d9(v0 int32) int32 {
	return i32_shl(i32_shr_s(v0, i32(1)), i32(1))
}
func (m *Module) Xi32_no_fold_shr_u_shl_vo7dit(v0 int32) int32 {
	return i32_shl(i32_shr_u(v0, i32(1)), i32(1))
}
func (m *Module) Xi64_no_fold_shr_s_shl_144pihh(v0 int64) int64 {
	return i64_shl(i64_shr_s(v0, i64(1)), i64(1))
}
func (m *Module) Xi64_no_fold_shr_u_shl_7oym5(v0 int64) int64 {
	return i64_shl(i64_shr_u(v0, i64(1)), i64(1))
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_s(x, y int32) int32 {
	return x >> (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i64_shl(x, y int64) int64 {
	return x << (y & 63)
}

//go:nosplit
func i64_shr_s(x, y int64) int64 {
	return x >> (y & 63)
}

//go:nosplit
func i64_shr_u(x, y int64) int64 {
	return int64(uint64(x) >> (y & 63))
}
