// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_ult(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 >= t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf32_ule(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 > t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf32_ugt(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 <= t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf32_uge(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 < t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf64_ult(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 >= t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf64_ule(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 > t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf64_ugt(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 <= t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
func (m *Module) Xf64_uge(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	var p2 int32
	if t0 < t1 {
		p2 = 1
	}
	var p3 int32
	if p2 == 0 {
		p3 = 1
	}
	return p3
}
