// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_lt_if(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	var t3 float32
	_ = t3
	if t0 < t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf32_no_fold_le_if(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	var t3 float32
	_ = t3
	if t0 <= t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf32_no_fold_gt_if(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	var t3 float32
	_ = t3
	if t0 > t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf32_no_fold_ge_if(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	var t3 float32
	_ = t3
	if t0 >= t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf64_no_fold_lt_if(v0 float64, v1 float64) float64 {
	t0 := v0
	t1 := v1
	var t3 float64
	_ = t3
	if t0 < t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf64_no_fold_le_if(v0 float64, v1 float64) float64 {
	t0 := v0
	t1 := v1
	var t3 float64
	_ = t3
	if t0 <= t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf64_no_fold_gt_if(v0 float64, v1 float64) float64 {
	t0 := v0
	t1 := v1
	var t3 float64
	_ = t3
	if t0 > t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
func (m *Module) Xf64_no_fold_ge_if(v0 float64, v1 float64) float64 {
	t0 := v0
	t1 := v1
	var t3 float64
	_ = t3
	if t0 >= t1 {
		t4 := v0
		t3 = t4
	} else {
		t5 := v1
		t3 = t5
	}
	return t3
}
