// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 1
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	return m
}
func (m *Module) Xf64_simple_x4_sum_1xixd6x(v0 int32, v1 int32, v2 int32) {
	var v3, v4, v5, v6, v7, v8, v9, v10 float64
	_, _, _, _, _, _, _, _ = v3, v4, v5, v6, v7, v8, v9, v10
	t0 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(v0):]))
	v3 = t0
	t1 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+8:]))
	v4 = t1
	t2 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+16:]))
	v5 = t2
	t3 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+24:]))
	v6 = t3
	t4 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(v1):]))
	v7 = t4
	t5 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v1))+8:]))
	v8 = t5
	t6 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v1))+16:]))
	v9 = t6
	t7 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[int64(uint32(v1))+24:]))
	v10 = t7
	binary.LittleEndian.PutUint64(m.memory[uint32(v2):], math.Float64bits(float64(v3+v7)))
	binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+8:], math.Float64bits(float64(v4+v8)))
	binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+16:], math.Float64bits(float64(v5+v9)))
	binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+24:], math.Float64bits(float64(v6+v10)))
}
func (m *Module) Xf64_load_1t7qcva(v0 int32) float64 {
	t0 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(v0):]))
	return t0
}

const data0 = "\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x80\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x80\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
