// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32응2Eno_fold_add_le_monotonicity(v0 float32, v1 float32, v2 float32) int32 {
	var p0 int32
	if float32(v0+v2) <= float32(v1+v2) {
		p0 = 1
	}
	return p0
}
func (m *Module) Xf32응2Eno_fold_add_ge_monotonicity(v0 float32, v1 float32, v2 float32) int32 {
	var p0 int32
	if float32(v0+v2) >= float32(v1+v2) {
		p0 = 1
	}
	return p0
}
func (m *Module) Xf64응2Eno_fold_add_le_monotonicity(v0 float64, v1 float64, v2 float64) int32 {
	var p0 int32
	if float64(v0+v2) <= float64(v1+v2) {
		p0 = 1
	}
	return p0
}
func (m *Module) Xf64응2Eno_fold_add_ge_monotonicity(v0 float64, v1 float64, v2 float64) int32 {
	var p0 int32
	if float64(v0+v2) >= float64(v1+v2) {
		p0 = 1
	}
	return p0
}
