// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_epsilon() float32 {
	t0 := float32(float32(4) / float32(3))
	t1 := float32(t0 - float32(1))
	t2 := float32(float32(3) * t1)
	t3 := float32(float32(1) - t2)
	return t3
}
func (m *Module) Xf64_epsilon() float64 {
	t0 := float64(float64(4) / float64(3))
	t1 := float64(t0 - float64(1))
	t2 := float64(float64(3) * t1)
	t3 := float64(float64(1) - t2)
	return t3
}
