// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	table    []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.table = make([]any, 10)
	m.elements = [][]any{[]any{m.f0, m.f1, m.f2}}
	copy(m.table[0:], m.elements[0])
	return m
}
func (m *Module) f0() int32 {
	return i32_const(0)
}
func (m *Module) f1() int32 {
	return int32(1)
}
func (m *Module) f2() int32 {
	return int32(2)
}
func (m *Module) Xcopy(v0 int32, v1 int32, v2 int32) {
	t0 := v0
	t1 := v1
	t2 := v2
	table_copy(m.table, m.table, t0, t1, t2)
}
func (m *Module) Xcall(v0 int32) int32 {
	t0 := v0
	t1 := m.table[uint32(t0)].(func() int32)()
	return t1
}

//go:nosplit
func i32_const(x int32) int32 { return x }

func table_copy(dst, tab []any, dest, src, n int32) {
	x := uint(uint32(dest))
	z := uint(uint32(src))
	y := x + uint(uint32(n))
	w := z + uint(uint32(n))
	copy(dst[x:y], tab[z:w])
}
