// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	g0       int32
	g1       float32
	g2       float64
	g3       int64
	g4       int32
	g5       float32
	g6       float64
	g7       int64
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.f26}}
	copy(m.t0[0:], m.elements[0])
	m.g0 = i32_const(-2)
	m.g1 = float32(-3)
	m.g2 = float64(-4)
	m.g3 = i64_const(-5)
	m.g4 = i32_const(-12)
	m.g5 = float32(-13)
	m.g6 = float64(-14)
	m.g7 = i64_const(-15)
	return m
}
func (m *Module) Xget응2Da() int32 {
	t0 := m.g0
	return t0
}
func (m *Module) Xget응2Db() int64 {
	t0 := m.g3
	return t0
}
func (m *Module) Xget응2Dx() int32 {
	t0 := m.g4
	return t0
}
func (m *Module) Xget응2Dy() int64 {
	t0 := m.g7
	return t0
}
func (m *Module) Xset응2Dx(v0 int32) {
	m.g4 = v0
}
func (m *Module) Xset응2Dy(v0 int64) {
	m.g7 = v0
}
func (m *Module) Xget응2D1() float32 {
	t0 := m.g1
	return t0
}
func (m *Module) Xget응2D2() float64 {
	t0 := m.g2
	return t0
}
func (m *Module) Xget응2D5() float32 {
	t0 := m.g5
	return t0
}
func (m *Module) Xget응2D6() float64 {
	t0 := m.g6
	return t0
}
func (m *Module) Xset응2D5(v0 float32) {
	m.g5 = v0
}
func (m *Module) Xset응2D6(v0 float64) {
	m.g6 = v0
}
func (m *Module) f12() {
}
func (m *Module) Xas응2Dselect응2Dfirst() int32 {
	t0 := m.g4
	p1 := int32(2)
	if int32(3) != 0 {
		p1 = t0
	}
	return p1
}
func (m *Module) Xas응2Dselect응2Dmid() int32 {
	t0 := m.g4
	p1 := t0
	if int32(3) != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas응2Dselect응2Dlast() int32 {
	t0 := m.g4
	p1 := int32(3)
	if t0 != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas응2Dloop응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		m.f12()
		m.f12()
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Dmid() int32 {
	var p0 int32
	_ = p0
	{
		m.f12()
		t1 := m.g4
		m.f12()
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		m.f12()
		m.f12()
		t1 := m.g4
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dif응2Dcondition() int32 {
	t0 := m.g4
	var p1 int32
	_ = p1
	if t0 != 0 {
		m.f12()
		p1 = int32(2)
	} else {
		m.f12()
		p1 = int32(3)
	}
	return p1
}
func (m *Module) Xas응2Dif응2Dthen() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		t1 := m.g4
		p0 = t1
	} else {
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas응2Dif응2Delse() int32 {
	var p0 int32
	_ = p0
	if i32_const(0) != 0 {
		p0 = int32(2)
	} else {
		t1 := m.g4
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dbr_if응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		if int32(2) != 0 {
			p0 = t1
			goto l0
		}
		return int32(3)
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_if응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		if t1 != 0 {
			p0 = int32(2)
			goto l0
		}
		return int32(3)
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		switch int32(2) {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		switch t1 {
		default:
			p0 = int32(2)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) f26(v0 int32, v1 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dcall_indirect응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		t2 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(t1, int32(2))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Dmid() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		t2 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(2), t1)
		p0 = t2
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		t2 := m.t0[uint(t1)].(func(v0 int32, v1 int32) int32)(int32(2), i32_const(0))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas응2Dstore응2Dfirst() {
	t0 := m.g4
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(int32(1)))
}
func (m *Module) Xas응2Dstore응2Dlast() {
	t0 := m.g4
	binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(t0))
}
func (m *Module) Xas응2Dload응2Doperand() int32 {
	t0 := m.g4
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xas응2Dmemory응2Egrow응2Dvalue() int32 {
	t0 := m.g4
	t1 := int32(memory_grow(&m.memory, int64(t0), m.maxMem))
	return t1
}
func (m *Module) f34(v0 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dcall응2Dvalue() int32 {
	t0 := m.g4
	t1 := m.f34(t0)
	return t1
}
func (m *Module) Xas응2Dreturn응2Dvalue() int32 {
	t0 := m.g4
	return t0
}
func (m *Module) Xas응2Ddrop응2Doperand() {
	t0 := m.g4
	_ = t0
}
func (m *Module) Xas응2Dbr응2Dvalue() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.g4
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas응2Dlocal응2Eset응2Dvalue(v0 int32) int32 {
	t0 := m.g4
	v0 = t0
	return v0
}
func (m *Module) Xas응2Dlocal응2Etee응2Dvalue(v0 int32) int32 {
	t0 := m.g4
	v0 = t0
	return v0
}
func (m *Module) Xas응2Dglobal응2Eset응2Dvalue() int32 {
	t0 := m.g4
	m.g4 = t0
	t1 := m.g4
	return t1
}
func (m *Module) Xas응2Dunary응2Doperand() int32 {
	t0 := m.g4
	var p1 int32
	if t0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas응2Dbinary응2Doperand() int32 {
	t0 := m.g4
	t1 := m.g4
	return t0 * t1
}
func (m *Module) Xas응2Dcompare응2Doperand() int32 {
	t0 := m.g0
	var p1 int32
	if uint32(t0) > uint32(int32(1)) {
		p1 = 1
	}
	return p1
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func i64_const(x int64) int64 { return x }

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
