// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_compute_radix(v0 float32, v1 float32) float32 {
l0:
	{
		v0 = float32(v0 + v0)
		if float32(float32(float32(v0+f32_const(1))-v0)+f32_const(-1)) == f32_const(0) {
			goto l0
		}
	}
l1:
	{
		t0 := v0
		v1 = float32(v1 + f32_const(1))
		if float32(float32(float32(t0+v1)-v0)-v1) != f32_const(0) {
			goto l1
		}
	}
	return v1
}
func (m *Module) Xf64_compute_radix(v0 float64, v1 float64) float64 {
l0:
	{
		v0 = float64(v0 + v0)
		if float64(float64(float64(v0+f64_const(1))-v0)+f64_const(-1)) == f64_const(0) {
			goto l0
		}
	}
l1:
	{
		t0 := v0
		v1 = float64(v1 + f64_const(1))
		if float64(float64(float64(t0+v1)-v0)-v1) != f64_const(0) {
			goto l1
		}
	}
	return v1
}

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
