// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xadd(v0 float64, v1 float64) float64 {
	return float64(v0 + v1)
}
func (m *Module) Xsub(v0 float64, v1 float64) float64 {
	return float64(v0 - v1)
}
func (m *Module) Xmul(v0 float64, v1 float64) float64 {
	return float64(v0 * v1)
}
func (m *Module) Xdiv(v0 float64, v1 float64) float64 {
	return float64(v0 / v1)
}
func (m *Module) Xsqrt(v0 float64) float64 {
	return math.Sqrt(v0)
}
func (m *Module) Xmin(v0 float64, v1 float64) float64 {
	return f64_min(v0, v1)
}
func (m *Module) Xmax(v0 float64, v1 float64) float64 {
	return f64_max(v0, v1)
}
func (m *Module) Xceil(v0 float64) float64 {
	return math.Ceil(v0)
}
func (m *Module) Xfloor(v0 float64) float64 {
	return math.Floor(v0)
}
func (m *Module) Xtrunc(v0 float64) float64 {
	return math.Trunc(v0)
}
func (m *Module) Xnearest(v0 float64) float64 {
	return math.RoundToEven(v0)
}

//go:nosplit
func f64_min(x, y float64) float64 {
	if m := min(x, y); m == m {
		return m
	}
	return math.Float64frombits(0x7ff8000000000000)
}

//go:nosplit
func f64_max(x, y float64) float64 {
	if m := max(x, y); m == m {
		return m
	}
	return math.Float64frombits(0x7ff8000000000000)
}
