// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	copy(m.memory[65528:], data1)
	return m
}
func (m *Module) Xi32_load(v0 int32) int32 {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xi64_load(v0 int32) int64 {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint64(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xf32_load(v0 int32) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xf64_load(v0 int32) float64 {
	t0 := v0
	t1 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xi32_load8_s(v0 int32) int32 {
	t0 := v0
	t1 := int32(int8(m.memory[uint32(t0)]))
	return t1
}
func (m *Module) Xi32_load8_u(v0 int32) int32 {
	t0 := v0
	t1 := int32(m.memory[uint32(t0)])
	return t1
}
func (m *Module) Xi32_load16_s(v0 int32) int32 {
	t0 := v0
	t1 := int32(int16(binary.LittleEndian.Uint16(m.memory[uint32(t0):])))
	return t1
}
func (m *Module) Xi32_load16_u(v0 int32) int32 {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint16(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xi64_load8_s(v0 int32) int64 {
	t0 := v0
	t1 := int64(int8(m.memory[uint32(t0)]))
	return t1
}
func (m *Module) Xi64_load8_u(v0 int32) int64 {
	t0 := v0
	t1 := int64(m.memory[uint32(t0)])
	return t1
}
func (m *Module) Xi64_load16_s(v0 int32) int64 {
	t0 := v0
	t1 := int64(int16(binary.LittleEndian.Uint16(m.memory[uint32(t0):])))
	return t1
}
func (m *Module) Xi64_load16_u(v0 int32) int64 {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint16(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xi64_load32_s(v0 int32) int64 {
	t0 := v0
	t1 := int64(int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):])))
	return t1
}
func (m *Module) Xi64_load32_u(v0 int32) int64 {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xi32_store(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}
func (m *Module) Xi64_store(v0 int32, v1 int64) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint64(m.memory[uint32(t0):], uint64(t1))
}
func (m *Module) Xf32_store(v0 int32, v1 float32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], math.Float32bits(t1))
}
func (m *Module) Xf64_store(v0 int32, v1 float64) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint64(m.memory[uint32(t0):], math.Float64bits(t1))
}
func (m *Module) Xi32_store8(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	m.memory[uint32(t0)] = byte(t1)
}
func (m *Module) Xi32_store16(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint16(m.memory[uint32(t0):], uint16(t1))
}
func (m *Module) Xi64_store8(v0 int32, v1 int64) {
	t0 := v0
	t1 := v1
	m.memory[uint32(t0)] = byte(t1)
}
func (m *Module) Xi64_store16(v0 int32, v1 int64) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint16(m.memory[uint32(t0):], uint16(t1))
}
func (m *Module) Xi64_store32(v0 int32, v1 int64) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}

const (
	data0 = "abcdefgh"
	data1 = "abcdefgh"
)
