// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 281474976710656
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data1)
	return m
}
func (m *Module) Xdrop_passive() {
}
func (m *Module) Xinit_passive() {
	memory64_init(m.memory, data0, i64_const(0), i32_const(0), i32_const(0))
}
func (m *Module) Xdrop_active() {
}
func (m *Module) Xinit_active() {
	memory64_init(m.memory, data1, i64_const(0), i32_const(0), i32_const(0))
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func i64_const(x int64) int64 { return x }

func memory64_init(mem []byte, data string, dest int64, src, n int32) {
	x := uint64(dest)
	z := uint64(uint32(src))
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], data[z:w])
}

const (
	data0 = ""
	data1 = ""
)
