// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xld16(v0 int32) int32 {
	t0 := int32(load16(m.memory, uint64(uint32(v0))))
	return t0
}
func (m *Module) Xld32(v0 int32) int32 {
	t0 := int32(load32(m.memory, uint64(uint32(v0))))
	return t0
}
func (m *Module) Xld64(v0 int32) int64 {
	t0 := int64(load64(m.memory, uint64(uint32(v0))))
	return t0
}
func (m *Module) Xld32o(v0 int32) int32 {
	t0 := int32(load32(m.memory, uint64(uint32(v0))+0xffffffff))
	return t0
}
func (m *Module) Xst32(v0, v1 int32) {
	store32(m.memory, uint64(uint32(v0)), uint32(v1))
}
func (m *Module) Xst64(v0 int32, v1 int64) {
	store64(m.memory, uint64(uint32(v0)), uint64(v1))
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func load16(mem []byte, addr uint64) uint16 {
	return binary.LittleEndian.Uint16(mem[addr:])
}

//go:nosplit
func load32(mem []byte, addr uint64) uint32 {
	return binary.LittleEndian.Uint32(mem[addr:])
}

//go:nosplit
func store32(mem []byte, addr uint64, val uint32) {
	binary.LittleEndian.PutUint32(mem[addr:], val)
}

//go:nosplit
func load64(mem []byte, addr uint64) uint64 {
	return binary.LittleEndian.Uint64(mem[addr:])
}

//go:nosplit
func store64(mem []byte, addr uint64, val uint64) {
	binary.LittleEndian.PutUint64(mem[addr:], val)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := int64(len(buf))
	old := len >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := new<<16 - len
	max = min(max, int64(math.MaxInt)>>16)
	if new > max || new < old || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
