// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_i32_no_fold_trunc_s_convert_s_1z8d7v(v0 float32) float32 {
	t0 := i32_trunc_f32_s(v0)
	return float32(t0)
}
func (m *Module) Xf32_i32_no_fold_trunc_u_convert_s_xwjk3i(v0 float32) float32 {
	t0 := i32_trunc_f32_u(v0)
	return float32(t0)
}
func (m *Module) Xf32_i32_no_fold_trunc_s_convert_u_9an2tf(v0 float32) float32 {
	t0 := i32_trunc_f32_s(v0)
	return float32(uint32(t0))
}
func (m *Module) Xf32_i32_no_fold_trunc_u_convert_u_pom3km(v0 float32) float32 {
	t0 := i32_trunc_f32_u(v0)
	return float32(uint32(t0))
}
func (m *Module) Xf64_i32_no_fold_trunc_s_convert_s_1oiwzir(v0 float64) float64 {
	t0 := i32_trunc_f64_s(v0)
	return float64(t0)
}
func (m *Module) Xf64_i32_no_fold_trunc_u_convert_s_1ae4nk6(v0 float64) float64 {
	t0 := i32_trunc_f64_u(v0)
	return float64(t0)
}
func (m *Module) Xf64_i32_no_fold_trunc_s_convert_u_1y29hdn(v0 float64) float64 {
	t0 := i32_trunc_f64_s(v0)
	return float64(uint32(t0))
}
func (m *Module) Xf64_i32_no_fold_trunc_u_convert_u_zy9bqm(v0 float64) float64 {
	t0 := i32_trunc_f64_u(v0)
	return float64(uint32(t0))
}
func (m *Module) Xf32_i64_no_fold_trunc_s_convert_s_1sbkvrw(v0 float32) float32 {
	t0 := i64_trunc_f32_s(v0)
	return float32(t0)
}
func (m *Module) Xf32_i64_no_fold_trunc_u_convert_s_16xt45l(v0 float32) float32 {
	t0 := i64_trunc_f32_u(v0)
	return float32(t0)
}
func (m *Module) Xf32_i64_no_fold_trunc_s_convert_u_1ho77sk(v0 float32) float32 {
	t0 := i64_trunc_f32_s(v0)
	return float32(uint64(t0))
}
func (m *Module) Xf32_i64_no_fold_trunc_u_convert_u_1g9n8o1(v0 float32) float32 {
	t0 := i64_trunc_f32_u(v0)
	return float32(uint64(t0))
}
func (m *Module) Xf64_i64_no_fold_trunc_s_convert_s_gblfxg(v0 float64) float64 {
	t0 := i64_trunc_f64_s(v0)
	return float64(t0)
}
func (m *Module) Xf64_i64_no_fold_trunc_u_convert_s_jwu5wx(v0 float64) float64 {
	t0 := i64_trunc_f64_u(v0)
	return float64(t0)
}
func (m *Module) Xf64_i64_no_fold_trunc_s_convert_u_7w5ij0(v0 float64) float64 {
	t0 := i64_trunc_f64_s(v0)
	return float64(uint64(t0))
}
func (m *Module) Xf64_i64_no_fold_trunc_u_convert_u_r0qgm1(v0 float64) float64 {
	t0 := i64_trunc_f64_u(v0)
	return float64(uint64(t0))
}

func i32_trunc_f64_s(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(x)
}

func i32_trunc_f32_s(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(x)
}

func i32_trunc_f64_u(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(uint32(x))
}

func i32_trunc_f32_u(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int32(uint32(x))
}

func i64_trunc_f64_s(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(x)
}

func i64_trunc_f32_s(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(x)
}

func i64_trunc_f64_u(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(uint64(x))
}

func i64_trunc_f32_u(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	case math.IsNaN(x):
		panic("invalid conversion to integer")
	}
	return int64(uint64(x))
}
