// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 10
	m.memory = make([]byte, 0)
	return m
}
func (m *Module) Xgrow(v0 int64) int64 {
	t0 := v0
	t1 := memory64_grow(&m.memory, t0, m.maxMem)
	return t1
}

func memory64_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len64 := int64(len(buf))
	old := len64 >> 16
	if delta == 0 {
		return old
	}
	newPages := old + delta
	add := (newPages << 16) - len64
	if newPages > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
