// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
	"runtime"
)

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	copy(m.memory[20:], data1)
	return m
}
func (m *Module) Xdata() int32 {
	t0 := int32(m.memory[uint32(i32_const(0))])
	var t1 int32
	if t0 == int32(65) {
		t1 = 1
	}
	t2 := int32(m.memory[uint32(int32(3))])
	var t3 int32
	if t2 == i32_const(167) {
		t3 = 1
	}
	t4 := t1 & t3
	t5 := int32(m.memory[uint32(int32(6))])
	var t6 int32
	if t5 == i32_const(0) {
		t6 = 1
	}
	t7 := int32(m.memory[uint32(int32(19))])
	var t8 int32
	if t7 == i32_const(0) {
		t8 = 1
	}
	t9 := t6 & t8
	t10 := t4 & t9
	t11 := int32(m.memory[uint32(int32(20))])
	var t12 int32
	if t11 == int32(87) {
		t12 = 1
	}
	t13 := int32(m.memory[uint32(int32(23))])
	var t14 int32
	if t13 == int32(77) {
		t14 = 1
	}
	t15 := t12 & t14
	t16 := int32(m.memory[uint32(int32(24))])
	var t17 int32
	if t16 == i32_const(0) {
		t17 = 1
	}
	t18 := int32(m.memory[uint32(i32_const(1023))])
	var t19 int32
	if t18 == i32_const(0) {
		t19 = 1
	}
	t20 := t17 & t19
	t21 := t15 & t20
	t22 := t10 & t21
	return t22
}
func (m *Module) Xcast() float64 {
	binary.LittleEndian.PutUint64(m.memory[uint32(int32(8)):], uint64(i64_const(-12345)))
	t0 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(int32(8)):]))
	t1 := math.Float64frombits(uint64(i64_const(-12345)))
	if t0 == t1 {
		return f64_const(0)
	}
	binary.LittleEndian.PutUint64(m.memory[uint32(int32(9)):], uint64(i64_const(0)))
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(15)):], uint16(i32_const(16453)))
	t3 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(int32(9)):]))
	return t3
}
func (m *Module) Xi32_load8_s(v0 int32) int32 {
	t0 := v0
	m.memory[uint32(int32(8))] = byte(t0)
	t1 := int32(int8(m.memory[uint32(int32(8))]))
	return t1
}
func (m *Module) Xi32_load8_u(v0 int32) int32 {
	t0 := v0
	m.memory[uint32(int32(8))] = byte(t0)
	t1 := int32(m.memory[uint32(int32(8))])
	return t1
}
func (m *Module) Xi32_load16_s(v0 int32) int32 {
	t0 := v0
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(8)):], uint16(t0))
	t1 := int32(int16(binary.LittleEndian.Uint16(m.memory[uint32(int32(8)):])))
	return t1
}
func (m *Module) Xi32_load16_u(v0 int32) int32 {
	t0 := v0
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(8)):], uint16(t0))
	t1 := int32(binary.LittleEndian.Uint16(m.memory[uint32(int32(8)):]))
	return t1
}
func (m *Module) Xi64_load8_s(v0 int64) int64 {
	t0 := v0
	m.memory[uint32(int32(8))] = byte(t0)
	t1 := int64(int8(m.memory[uint32(int32(8))]))
	return t1
}
func (m *Module) Xi64_load8_u(v0 int64) int64 {
	t0 := v0
	m.memory[uint32(int32(8))] = byte(t0)
	t1 := int64(m.memory[uint32(int32(8))])
	return t1
}
func (m *Module) Xi64_load16_s(v0 int64) int64 {
	t0 := v0
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(8)):], uint16(t0))
	t1 := int64(int16(binary.LittleEndian.Uint16(m.memory[uint32(int32(8)):])))
	return t1
}
func (m *Module) Xi64_load16_u(v0 int64) int64 {
	t0 := v0
	binary.LittleEndian.PutUint16(m.memory[uint32(int32(8)):], uint16(t0))
	t1 := int64(binary.LittleEndian.Uint16(m.memory[uint32(int32(8)):]))
	return t1
}
func (m *Module) Xi64_load32_s(v0 int64) int64 {
	t0 := v0
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(t0))
	t1 := int64(int32(binary.LittleEndian.Uint32(m.memory[uint32(int32(8)):])))
	return t1
}
func (m *Module) Xi64_load32_u(v0 int64) int64 {
	t0 := v0
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(8)):], uint32(t0))
	t1 := int64(binary.LittleEndian.Uint32(m.memory[uint32(int32(8)):]))
	return t1
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func i64_const(x int64) int64 { return x }

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}

const (
	data0 = "ABC\xa7D"
	data1 = "WASM"
)
