// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_div_s_5(v0 int32) int32 {
	t0 := v0
	t1 := i32_div_s(t0, int32(5))
	return t1
}
func (m *Module) Xi32_div_u_5(v0 int32) int32 {
	t0 := v0
	t1 := int32(uint32(t0) / uint32(int32(5)))
	return t1
}
func (m *Module) Xi64_div_s_5(v0 int64) int64 {
	t0 := v0
	t1 := i64_div_s(t0, int64(5))
	return t1
}
func (m *Module) Xi64_div_u_5(v0 int64) int64 {
	t0 := v0
	t1 := int64(uint64(t0) / uint64(int64(5)))
	return t1
}

func i32_div_s(x, y int32) int32 {
	if x == math.MinInt32 && y == -1 {
		panic("integer overflow")
	}
	return x / y
}

func i64_div_s(x, y int64) int64 {
	if x == math.MinInt64 && y == -1 {
		panic("integer overflow")
	}
	return x / y
}
