// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_trichotomy_lt_1h5i1ui(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if v0 >= v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf32_no_trichotomy_le_pzf0dy(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if v0 > v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf32_no_trichotomy_gt_67mz23(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if v0 <= v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf32_no_trichotomy_ge_1vsmxzr(v0 float32, v1 float32) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if v0 < v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf64_no_trichotomy_lt_1kasgjd(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 < v1 {
		p0 = 1
	}
	var p1 int32
	if v0 >= v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf64_no_trichotomy_le_bc6evp(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 <= v1 {
		p0 = 1
	}
	var p1 int32
	if v0 > v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf64_no_trichotomy_gt_rhxrq0(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 > v1 {
		p0 = 1
	}
	var p1 int32
	if v0 <= v1 {
		p1 = 1
	}
	return p0 | p1
}
func (m *Module) Xf64_no_trichotomy_ge_zuclx0(v0 float64, v1 float64) int32 {
	var p0 int32
	if v0 >= v1 {
		p0 = 1
	}
	var p1 int32
	if v0 < v1 {
		p1 = 1
	}
	return p0 | p1
}
