// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 281474976710656
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	return m
}
func (m *Module) X32_good1(v0 int64) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0:]))
	return t1
}
func (m *Module) X32_good2(v0 int64) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0:]))
	return t1
}
func (m *Module) X32_good3(v0 int64) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0+1|t0>>63:]))
	return t1
}
func (m *Module) X32_good4(v0 int64) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0+2|t0>>63:]))
	return t1
}
func (m *Module) X32_good5(v0 int64) float32 {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0+8|t0>>63:]))
	return t1
}
func (m *Module) X32_bad(v0 int64) {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[t0+4294967295|t0>>63:]))
	_ = t1
}

const data0 = "\x00\x00\x00\x00\x00\x00\xa0\x7f\x01\x00\xd0\x7f"
