// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	_ "embed"
	"testing"

	"github.com/ncruces/wasm2go/spectest"
)

//go:embed address64.2.json
var data []byte

func Test(t *testing.T) {
	spectest.Test(t, New(), data, "address64.2.wasm")
}
