// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	t1       []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 2)
	m.t1 = make([]any, 2)
	m.elements = [][]any{{m.f2}}
	copy(m.t0[1:], m.elements[0])
	return m
}
func (m *Module) Xfuncref(v0 any) int32 {
	var p0 int32
	if v0 == nil {
		p0 = 1
	}
	return p0
}
func (m *Module) Xexternref(v0 any) int32 {
	var p0 int32
	if v0 == nil {
		p0 = 1
	}
	return p0
}
func (m *Module) f2() {
}
func (m *Module) Xinit(v0 any) {
	m.t1[int32(1)] = v0
}
func (m *Module) Xdeinit() {
	m.t0[int32(1)] = nil
	m.t1[int32(1)] = nil
}
func (m *Module) Xfuncref응2Delem(v0 int32) int32 {
	t0 := m.t0[v0]
	t1 := m.Xfuncref(t0)
	return t1
}
func (m *Module) Xexternref응2Delem(v0 int32) int32 {
	t0 := m.t1[v0]
	t1 := m.Xexternref(t0)
	return t1
}
