// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xllvm_pr27036(v0 int32, v1 int32) float32 {
	t0 := v0
	t1 := t0 | i32_const(-25034805)
	t2 := float32(t1)
	t3 := v1
	t4 := t3 & i32_const(14942208)
	t5 := float32(t4)
	t6 := float32(t2 + t5)
	return t6
}

func i32_const(x int32) int32 { return x }
