// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xadd(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 + t1)
	return t2
}
func (m *Module) Xsub(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 - t1)
	return t2
}
func (m *Module) Xmul(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 * t1)
	return t2
}
func (m *Module) Xdiv(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 / t1)
	return t2
}
func (m *Module) Xsqrt(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.Sqrt(float64(t0)))
	return t1
}
func (m *Module) Xmin(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := min(t0, t1)
	return t2
}
func (m *Module) Xmax(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := max(t0, t1)
	return t2
}
func (m *Module) Xceil(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.Ceil(float64(t0)))
	return t1
}
func (m *Module) Xfloor(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.Floor(float64(t0)))
	return t1
}
func (m *Module) Xtrunc(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.Trunc(float64(t0)))
	return t1
}
func (m *Module) Xnearest(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.RoundToEven(float64(t0)))
	return t1
}
