// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 281474976710656
	m.memory = make([]byte, 0)
	return m
}
func (m *Module) Xgrow(v0 int64) int64 {
	t0 := v0
	t1 := int64(memory_grow(&m.memory, int64(t0), m.maxMem))
	return t1
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
