// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_silver_means(v0 float32) float32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := float32(t1 * t2)
	t4 := float32(t3 + float32(4))
	t5 := float32(math.Sqrt(float64(t4)))
	t6 := float32(t0 + t5)
	t7 := float32(float32(0.5) * t6)
	return t7
}
func (m *Module) Xf64_silver_means(v0 float64) float64 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := float64(t1 * t2)
	t4 := float64(t3 + float64(4))
	t5 := math.Sqrt(t4)
	t6 := float64(t0 + t5)
	t7 := float64(float64(0.5) * t6)
	return t7
}
