// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	copy(m.memory[uint32(i32(0)):], data0)
	return m
}
func (m *Module) X32_good1(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) X32_good2(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) X32_good3(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+1:]))
	return t0
}
func (m *Module) X32_good4(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+2:]))
	return t0
}
func (m *Module) X32_good5(v0 int32) float32 {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) X32_bad(v0 int32) {
	t0 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4294967295:]))
	_ = t0
}

//go:nosplit
func i32(x int32) int32 { return x }

const data0 = "\x00\x00\x00\x00\x00\x00\xa0\x7f\x01\x00\xd0\x7f"
