// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_incorrect_correction() float32 {
	t0 := float32(float32(1.333) + float32(1.225))
	t1 := float32(t0 - float32(1.333))
	t2 := float32(t1 - float32(1.225))
	return t2
}
func (m *Module) Xf64_incorrect_correction() float64 {
	t0 := float64(float64(1.333) + float64(1.225))
	t1 := float64(t0 - float64(1.333))
	t2 := float64(t1 - float64(1.225))
	return t2
}
