// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32응2Eno_regroup_div_mul(v0 float32, v1 float32, v2 float32) float32 {
	return float32(v0 * float32(v1/v2))
}
func (m *Module) Xf64응2Eno_regroup_div_mul(v0 float64, v1 float64, v2 float64) float64 {
	return float64(v0 * float64(v1/v2))
}
