// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory *[]byte
	Memory Memory
	maxMem int64
	_Mm    XMm
}

func New(v0 XMm) *Module {
	m := &Module{}
	m._Mm = v0
	m.maxMem = 65536
	m.Memory = v0.Xmem()
	m.memory = m.Memory.Slice()
	copy((*m.memory)[uint32(i32(5)):], data0)
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type XMm = interface {
	Xmem() Memory
}
type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}

func (m *Module) Xload(v0 int32) int32 {
	t0 := int32((*m.memory)[uint32(v0)])
	return t0
}

//go:nosplit
func i32(x int32) int32 { return x }

const data0 = "\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7"
