// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_no_fold_shl_shr_s_1dvg5ba(v0 int32) int32 {
	return i32_shr_s(i32_shl(v0, int32(1)), int32(1))
}
func (m *Module) Xi32_no_fold_shl_shr_u_15didji(v0 int32) int32 {
	return i32_shr_u(i32_shl(v0, int32(1)), int32(1))
}
func (m *Module) Xi64_no_fold_shl_shr_s_1hnfj72(v0 int64) int64 {
	return i64_shr_s(i64_shl(v0, int64(1)), int64(1))
}
func (m *Module) Xi64_no_fold_shl_shr_u_1sdagau(v0 int64) int64 {
	return i64_shr_u(i64_shl(v0, int64(1)), int64(1))
}

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_s(x, y int32) int32 {
	return x >> (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i64_shl(x, y int64) int64 {
	return x << (y & 63)
}

//go:nosplit
func i64_shr_s(x, y int64) int64 {
	return x >> (y & 63)
}

//go:nosplit
func i64_shr_u(x, y int64) int64 {
	return int64(uint64(x) >> (y & 63))
}
