// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       *[]any
	elements [][]any
	_Mt      XMt
}

func New(v0 XMt) *Module {
	m := &Module{}
	m._Mt = v0
	m.t0 = v0.Xtab()
	m.elements = [][]any{{m.f1, m.f0}}
	copy((*m.t0)[1:], m.elements[0])
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type XMt interface {
	Xh() int32
	Xtab() *[]any
}

func (m *Module) f0() int32 {
	return m._Mt.Xh()
}
func (m *Module) f1() int32 {
	return int32(6)
}
func (m *Module) Xcall(v0 int32) int32 {
	t0 := v0
	t1 := (*m.t0)[uint32(t0)].(func() int32)()
	return t1
}
