// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_rem_s_7(v0 int32) int32 {
	t0 := v0
	t1 := t0 % int32(7)
	return t1
}
func (m *Module) Xi32_rem_u_7(v0 int32) int32 {
	t0 := v0
	t1 := int32(uint32(t0) % uint32(int32(7)))
	return t1
}
func (m *Module) Xi64_rem_s_7(v0 int64) int64 {
	t0 := v0
	t1 := t0 % int64(7)
	return t1
}
func (m *Module) Xi64_rem_u_7(v0 int64) int64 {
	t0 := v0
	t1 := int64(uint64(t0) % uint64(int64(7)))
	return t1
}
