// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) Xno_dce_i32_load(v0 int32) {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_i32_load16_s(v0 int32) {
	t0 := v0
	t1 := int32(int16(binary.LittleEndian.Uint16(m.memory[uint32(t0):])))
	_ = t1
}
func (m *Module) Xno_dce_i32_load16_u(v0 int32) {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint16(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_i32_load8_s(v0 int32) {
	t0 := v0
	t1 := int32(int8(m.memory[uint32(t0)]))
	_ = t1
}
func (m *Module) Xno_dce_i32_load8_u(v0 int32) {
	t0 := v0
	t1 := int32(m.memory[uint32(t0)])
	_ = t1
}
func (m *Module) Xno_dce_i64_load(v0 int32) {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint64(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_i64_load32_s(v0 int32) {
	t0 := v0
	t1 := int64(int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):])))
	_ = t1
}
func (m *Module) Xno_dce_i64_load32_u(v0 int32) {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_i64_load16_s(v0 int32) {
	t0 := v0
	t1 := int64(int16(binary.LittleEndian.Uint16(m.memory[uint32(t0):])))
	_ = t1
}
func (m *Module) Xno_dce_i64_load16_u(v0 int32) {
	t0 := v0
	t1 := int64(binary.LittleEndian.Uint16(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_i64_load8_s(v0 int32) {
	t0 := v0
	t1 := int64(int8(m.memory[uint32(t0)]))
	_ = t1
}
func (m *Module) Xno_dce_i64_load8_u(v0 int32) {
	t0 := v0
	t1 := int64(m.memory[uint32(t0)])
	_ = t1
}
func (m *Module) Xno_dce_f32_load(v0 int32) {
	t0 := v0
	t1 := math.Float32frombits(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	_ = t1
}
func (m *Module) Xno_dce_f64_load(v0 int32) {
	t0 := v0
	t1 := math.Float64frombits(binary.LittleEndian.Uint64(m.memory[uint32(t0):]))
	_ = t1
}
