// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xfac_rec_1fbj6q6(v0 int64) int64 {
	var p0 int64
	_ = p0
	if v0 == i64(0) {
		p0 = i64(1)
	} else {
		t2 := v0
		t1 := m.Xfac_rec_1fbj6q6(v0 - i64(1))
		t3 := t2 * t1
		p0 = t3
	}
	return p0
}
func (m *Module) Xfac_rec_named_1b9t6xp(v0 int64) int64 {
	var p0 int64
	_ = p0
	if v0 == i64(0) {
		p0 = i64(1)
	} else {
		t2 := v0
		t1 := m.Xfac_rec_named_1b9t6xp(v0 - i64(1))
		t3 := t2 * t1
		p0 = t3
	}
	return p0
}
func (m *Module) Xfac_iter_u670pf(v0 int64) int64 {
	var v1, v2 int64
	_, _ = v1, v2
	v1 = v0
	v2 = i64(1)
l1:
	{
		if v1 == i64(0) {
			goto l0
		} else {
			v2 = v1 * v2
			v1 = v1 - i64(1)
		}
		goto l1
	}
l0:
	return v2
}
func (m *Module) Xfac_iter_named_1yyaicc(v0 int64) int64 {
	var v1, v2 int64
	_, _ = v1, v2
	v1 = v0
	v2 = i64(1)
l1:
	{
		if v1 == i64(0) {
			goto l0
		} else {
			v2 = v1 * v2
			v1 = v1 - i64(1)
		}
		goto l1
	}
l0:
	return v2
}
func (m *Module) Xfac_opt_uhnu4r(v0 int64) int64 {
	var v1 int64
	_ = v1
	v1 = i64(1)
	if v0 < i64(2) {
		goto l0
	}
l1:
	{
		v1 = v1 * v0
		v0 = v0 + i64(-1)
		if v0 > i64(1) {
			goto l1
		}
	}
l0:
	return v1
}
func (m *Module) f5(v0 int64) (int64, int64) {
	return v0, v0
}
func (m *Module) f6(v0 int64, v1 int64) (int64, int64, int64) {
	return v0, v1, v0
}
func (m *Module) Xfac_ssa_1bbbw1g(v0 int64) int64 {
	t1 := v0
	var p0 int64
	_ = p0
	p3, p2 := i64(1), t1
l0:
	{
		t4, t5, t6 := m.f6(p3, p2)
		t7, t8, t9 := m.f6(t5, t6)
		t10, t11, t12 := m.f6(t7, t8*t9)
		t13, t14 := m.f5(t12 - i64(1))
		if uint64(t14) > uint64(i64(0)) {
			p3, p2 = t11, t13
			goto l0
		}
		_ = t10
		return t4
	}
}

//go:nosplit
func i64(x int64) int64 { return x }
