// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xblock() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(1)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xloop1() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
	l1:
		{
			v0 = v0 + i32(1)
			if v0 == i32(5) {
				t2 := v0
				p0 = t2
				goto l0
			}
			goto l1
		}
	}
l0:
	return p0
}
func (m *Module) Xloop2() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
	l0:
		{
			v0 = v0 + i32(1)
			if v0 == i32(5) {
				goto l0
			}
			if v0 == i32(8) {
				t2 := v0
				p0 = t2
				goto l1
			}
			v0 = v0 + i32(1)
			goto l0
		}
	}
l1:
	return p0
}
func (m *Module) Xloop3() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			v0 = v0 + i32(1)
			if v0 == i32(5) {
				t2 := v0
				p0 = t2
				goto l0
			}
			t3 := v0
			p1 = t3
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xloop4(v0 int32) int32 {
	var v1 int32
	_ = v1
	v1 = i32(1)
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
	l1:
		{
			v1 = v1 + v1
			if uint32(v1) > uint32(v0) {
				t2 := v1
				p0 = t2
				goto l0
			}
			goto l1
		}
	}
l0:
	return p0
}
func (m *Module) Xloop5() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(1)
	}
	return p0 + i32(1)
}
func (m *Module) Xloop6() int32 {
	var p0 int32
	_ = p0
l0:
	{
		if i32(0) != 0 {
			goto l0
		}
		p0 = i32(3)
	}
	return p0
}
func (m *Module) Xif() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	{
		if i32(1) != 0 {
			goto l0
		}
	l0:
		v0 = v0 + i32(1)
		if i32(1) != 0 {
			goto l1
		} else {
			v0 = i32(888)
		}
	l1:
		v0 = v0 + i32(1)
		if i32(1) != 0 {
			goto l2
		} else {
			v0 = i32(888)
		}
	l2:
		v0 = v0 + i32(1)
		if i32(0) != 0 {
			v0 = i32(888)
		} else {
			goto l3
		}
	l3:
		v0 = v0 + i32(1)
		if i32(0) != 0 {
			v0 = i32(888)
		} else {
			goto l4
		}
	l4:
		v0 = v0 + i32(1)
	}
	return v0
}
func (m *Module) Xif2() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	{
		if i32(1) != 0 {
			goto l0
		}
	l0:
		v0 = v0 + i32(1)
		if i32(1) != 0 {
			goto l1
		} else {
			v0 = i32(888)
		}
	l1:
		v0 = v0 + i32(1)
		if i32(1) != 0 {
			goto l2
		} else {
			v0 = i32(888)
		}
	l2:
		v0 = v0 + i32(1)
		if i32(0) != 0 {
			v0 = i32(888)
		} else {
			goto l3
		}
	l3:
		v0 = v0 + i32(1)
		if i32(0) != 0 {
			v0 = i32(888)
		} else {
			goto l4
		}
	l4:
		v0 = v0 + i32(1)
	}
	return v0
}
func (m *Module) Xswitch(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			{
				{
					{
						{
							{
								switch v0 {
								case 0:
									goto l0
								case 1:
									goto l1
								case 2:
									goto l2
								case 3:
									goto l3
								default:
									goto l4
								}
							}
						l1:
						}
					l2:
						p1 = i32(2)
						goto l5
					}
				l3:
					p0 = i32(3)
					goto l6
				}
			l4:
			}
		l0:
			p1 = i32(5)
		}
	l5:
		t2 := i32(10) * p1
		p0 = t2
	}
l6:
	return p0
}
func (m *Module) Xreturn(v0 int32) int32 {
	{
		{
			{
				switch v0 {
				case 0:
					goto l0
				default:
					goto l1
				}
			}
		l0:
			return i32(0)
		}
	l1:
	}
	return i32(2)
}
func (m *Module) Xbr_if0() int32 {
	var v0 int32
	_ = v0
	v0 = i32(0)
	var p0 int32
	_ = p0
	{
		{
			if i32(0) != 0 {
				goto l0
			}
			v0 = v0 | i32(1)
			if i32(1) != 0 {
				goto l0
			}
			v0 = v0 | i32(2)
		}
	l0:
		;
		var p1 int32
		_ = p1
		{
			v0 = v0 | i32(4)
			t2 := v0
			p1 = t2
		}
		if i32(0) != 0 {
			p0 = p1
			goto l1
		}
		_ = p1
		v0 = v0 | i32(8)
		var p3 int32
		_ = p3
		{
			v0 = v0 | i32(16)
			t4 := v0
			p3 = t4
		}
		if i32(1) != 0 {
			p0 = p3
			goto l1
		}
		_ = p3
		v0 = v0 | i32(32)
		t5 := v0
		p0 = t5
	}
l1:
	return p0
}
func (m *Module) Xbr_if1() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = i32(1)
			goto l0
		}
	l0:
		if i32(1) != 0 {
			p0 = p1
			goto l1
		}
		_ = p1
		p0 = i32(0)
	}
l1:
	return p0
}
func (m *Module) Xbr_if2() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			var p1 int32
			_ = p1
			{
				p1 = i32(1)
				goto l0
			}
		l0:
			if i32(1) != 0 {
				p0 = p1
				goto l1
			}
			_ = p1
		}
		p0 = i32(0)
	}
l1:
	return p0
}
func (m *Module) Xbr_if3() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			v0 = i32(1)
			t2 := v0
			p1 = t2
		}
		var p3 int32
		_ = p3
		{
			v0 = i32(2)
			t4 := v0
			p3 = t4
		}
		if p3 != 0 {
			p0 = p1
			goto l0
		}
		_ = p1
		p0 = i32(0)
	}
l0:
	_ = p0 + i32(0)
	return v0
}
func (m *Module) Xbr() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			var p1 int32
			_ = p1
			{
				p1 = i32(1)
				goto l0
			}
		l0:
			p0 = p1
			goto l1
		} else {
			{
				var p2 int32
				_ = p2
				{
					p2 = i32(1)
					goto l2
				}
			l2:
				_ = p2
			}
		}
		p0 = i32(1)
	}
l1:
	return p0
}
func (m *Module) Xshadowing() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(1)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xredefinition() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = i32(2)
		}
		var p2 int32
		_ = p2
		{
			p2 = i32(3)
			goto l0
		}
	l0:
		t3 := p1 + p2
		p0 = t3
	}
	return p0
}

//go:nosplit
func i32(x int32) int32 { return x }
