// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xblock() int32 {
	var t0 int32
	_ = t0
	{
		t0 = int32(1)
		goto l0
	}
l0:
	return t0
}
func (m *Module) Xloop1() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
	l1:
		{
			t2 := v0
			t3 := t2 + int32(1)
			v0 = t3
			t4 := v0
			if t4 == int32(5) {
				t6 := v0
				t0 = t6
				goto l0
			}
			goto l1
		}
	}
l0:
	return t0
}
func (m *Module) Xloop2() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
	l0:
		{
			t2 := v0
			t3 := t2 + int32(1)
			v0 = t3
			t4 := v0
			if t4 == int32(5) {
				goto l0
			}
			t6 := v0
			if t6 == int32(8) {
				t8 := v0
				t0 = t8
				goto l1
			}
			t9 := v0
			t10 := t9 + int32(1)
			v0 = t10
			goto l0
		}
	}
l1:
	return t0
}
func (m *Module) Xloop3() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			t2 := v0
			t3 := t2 + int32(1)
			v0 = t3
			t4 := v0
			if t4 == int32(5) {
				t6 := v0
				t0 = t6
				goto l0
			}
			t7 := v0
			t1 = t7
		}
		t0 = t1
	}
l0:
	return t0
}
func (m *Module) Xloop4(v0 int32) int32 {
	var v1 int32
	_ = v1
	v1 = int32(1)
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
	l1:
		{
			t2 := v1
			t3 := v1
			t4 := t2 + t3
			v1 = t4
			t5 := v1
			t6 := v0
			if uint32(t5) > uint32(t6) {
				t8 := v1
				t0 = t8
				goto l0
			}
			goto l1
		}
	}
l0:
	return t0
}
func (m *Module) Xloop5() int32 {
	var t0 int32
	_ = t0
	{
		t0 = int32(1)
	}
	t1 := t0 + int32(1)
	return t1
}
func (m *Module) Xloop6() int32 {
	var t0 int32
	_ = t0
l0:
	{
		if i32_const(0) != 0 {
			goto l0
		}
		t0 = int32(3)
	}
	return t0
}
func (m *Module) Xif() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	{
		if int32(1) != 0 {
			goto l0
		}
	l0:
		t0 := v0
		t1 := t0 + int32(1)
		v0 = t1
		if int32(1) != 0 {
			goto l1
		} else {
			v0 = i32_const(888)
		}
	l1:
		t2 := v0
		t3 := t2 + int32(1)
		v0 = t3
		if int32(1) != 0 {
			goto l2
		} else {
			v0 = i32_const(888)
		}
	l2:
		t4 := v0
		t5 := t4 + int32(1)
		v0 = t5
		if i32_const(0) != 0 {
			v0 = i32_const(888)
		} else {
			goto l3
		}
	l3:
		t6 := v0
		t7 := t6 + int32(1)
		v0 = t7
		if i32_const(0) != 0 {
			v0 = i32_const(888)
		} else {
			goto l4
		}
	l4:
		t8 := v0
		t9 := t8 + int32(1)
		v0 = t9
	}
	t10 := v0
	return t10
}
func (m *Module) Xif2() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	{
		if int32(1) != 0 {
			goto l0
		}
	l0:
		t0 := v0
		t1 := t0 + int32(1)
		v0 = t1
		if int32(1) != 0 {
			goto l1
		} else {
			v0 = i32_const(888)
		}
	l1:
		t2 := v0
		t3 := t2 + int32(1)
		v0 = t3
		if int32(1) != 0 {
			goto l2
		} else {
			v0 = i32_const(888)
		}
	l2:
		t4 := v0
		t5 := t4 + int32(1)
		v0 = t5
		if i32_const(0) != 0 {
			v0 = i32_const(888)
		} else {
			goto l3
		}
	l3:
		t6 := v0
		t7 := t6 + int32(1)
		v0 = t7
		if i32_const(0) != 0 {
			v0 = i32_const(888)
		} else {
			goto l4
		}
	l4:
		t8 := v0
		t9 := t8 + int32(1)
		v0 = t9
	}
	t10 := v0
	return t10
}
func (m *Module) Xswitch(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			{
				{
					{
						{
							{
								t2 := v0
								switch t2 {
								default:
									goto l0
								case 0:
									goto l1
								case 1:
									goto l2
								case 2:
									goto l3
								case 3:
									goto l4
								}
							}
						l2:
						}
					l3:
						t1 = int32(2)
						goto l5
					}
				l4:
					t0 = int32(3)
					goto l6
				}
			l0:
			}
		l1:
			t1 = int32(5)
		}
	l5:
		t3 := int32(10) * t1
		t0 = t3
	}
l6:
	return t0
}
func (m *Module) Xreturn(v0 int32) int32 {
	{
		{
			{
				t0 := v0
				switch t0 {
				default:
					goto l0
				case 0:
					goto l1
				}
			}
		l1:
			return i32_const(0)
		}
	l0:
	}
	return int32(2)
}
func (m *Module) Xbr_if0() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	var t0 int32
	_ = t0
	{
		{
			if i32_const(0) != 0 {
				goto l0
			}
			t1 := v0
			t2 := t1 | int32(1)
			v0 = t2
			if int32(1) != 0 {
				goto l0
			}
			t3 := v0
			t4 := t3 | int32(2)
			v0 = t4
		}
	l0:
		;
		var t5 int32
		_ = t5
		{
			t6 := v0
			t7 := t6 | int32(4)
			v0 = t7
			t8 := v0
			t5 = t8
		}
		t0 = t5
		if i32_const(0) != 0 {
			goto l1
		}
		_ = t5
		t9 := v0
		t10 := t9 | int32(8)
		v0 = t10
		var t11 int32
		_ = t11
		{
			t12 := v0
			t13 := t12 | int32(16)
			v0 = t13
			t14 := v0
			t11 = t14
		}
		t0 = t11
		if int32(1) != 0 {
			goto l1
		}
		_ = t11
		t15 := v0
		t16 := t15 | int32(32)
		v0 = t16
		t17 := v0
		t0 = t17
	}
l1:
	return t0
}
func (m *Module) Xbr_if1() int32 {
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			t1 = int32(1)
			goto l0
		}
	l0:
		t0 = t1
		if int32(1) != 0 {
			goto l1
		}
		_ = t1
		t0 = i32_const(0)
	}
l1:
	return t0
}
func (m *Module) Xbr_if2() int32 {
	var t0 int32
	_ = t0
	{
		if int32(1) != 0 {
			var t1 int32
			_ = t1
			{
				t1 = int32(1)
				goto l0
			}
		l0:
			t0 = t1
			if int32(1) != 0 {
				goto l1
			}
			_ = t1
		}
		t0 = i32_const(0)
	}
l1:
	return t0
}
func (m *Module) Xbr_if3() int32 {
	var v0 int32
	_ = v0
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			v0 = int32(1)
			t2 := v0
			t1 = t2
		}
		var t3 int32
		_ = t3
		{
			v0 = int32(2)
			t4 := v0
			t3 = t4
		}
		t0 = t1
		if t3 != 0 {
			goto l0
		}
		_ = t1
		t0 = i32_const(0)
	}
l0:
	t5 := t0 + i32_const(0)
	_ = t5
	t6 := v0
	return t6
}
func (m *Module) Xbr() int32 {
	var t0 int32
	_ = t0
	{
		if int32(1) != 0 {
			var t1 int32
			_ = t1
			{
				t1 = int32(1)
				goto l0
			}
		l0:
			t0 = t1
			goto l1
		} else {
			{
				var t2 int32
				_ = t2
				{
					t2 = int32(1)
					goto l2
				}
			l2:
				_ = t2
			}
		}
		t0 = int32(1)
	}
l1:
	return t0
}
func (m *Module) Xshadowing() int32 {
	var t0 int32
	_ = t0
	{
		t0 = int32(1)
		goto l0
	}
l0:
	return t0
}
func (m *Module) Xredefinition() int32 {
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			t1 = int32(2)
		}
		var t2 int32
		_ = t2
		{
			t2 = int32(3)
			goto l0
		}
	l0:
		t3 := t1 + t2
		t0 = t3
	}
	return t0
}

func i32_const(x int32) int32 { return x }
