// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_rem_s_5_1i63oeb(v0 int32) int32 {
	t0 := v0 % i32(5)
	return t0
}
func (m *Module) Xi32_rem_u_5_557zv8(v0 int32) int32 {
	t0 := int32(uint32(v0) % uint32(i32(5)))
	return t0
}
func (m *Module) Xi64_rem_s_5_6rgzeb(v0 int64) int64 {
	t0 := v0 % i64(5)
	return t0
}
func (m *Module) Xi64_rem_u_5_1k10un8(v0 int64) int64 {
	t0 := int64(uint64(v0) % uint64(i64(5)))
	return t0
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }
