// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_div_neg1(v0 float32) float32 {
	t0 := v0
	t1 := float32(t0 / float32(-1))
	return t1
}
func (m *Module) Xf64_no_fold_div_neg1(v0 float64) float64 {
	t0 := v0
	t1 := float64(t0 / float64(-1))
	return t1
}
