// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	elements [][]any
	_Mt      XMt
}

func New(v0 XMt) *Module {
	m := &Module{}
	m._Mt = v0
	m.t0 = make([]any, 5)
	m.elements = [][]any{{m.f2, m.f2, m.f2, m.f1, m.XMt_call}}
	copy(m.t0[0:], m.elements[0])
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type XMt = interface {
	Xcall(v0 int32) int32
	Xh() int32
}

func (m *Module) XMt_call(v0 int32) int32 {
	return m._Mt.Xcall(v0)
}
func (m *Module) f1() int32 {
	return m._Mt.Xh()
}
func (m *Module) f2() int32 {
	return int32(5)
}
func (m *Module) Xcall_Mt_call(v0 int32) int32 {
	t0 := m.XMt_call(v0)
	return t0
}
func (m *Module) Xcall(v0 int32) int32 {
	t0 := m.t0[uint(v0)].(func() int32)()
	return t0
}
