// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_golden_ratio(v0 float32, v1 float32, v2 float32) float32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := float32(math.Sqrt(float64(t2)))
	t4 := float32(t1 + t3)
	t5 := float32(t0 * t4)
	return t5
}
func (m *Module) Xf64_golden_ratio(v0 float64, v1 float64, v2 float64) float64 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := math.Sqrt(t2)
	t4 := float64(t1 + t3)
	t5 := float64(t0 * t4)
	return t5
}
