// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 2)
	m.elements = [][]any{[]any{m.f0, m.f1}}
	copy(m.t0[0:], m.elements[0])
	return m
}
func (m *Module) f0() int32 {
	return int32(1)
}
func (m *Module) f1() int32 {
	return int32(2)
}
func (m *Module) Xcallt(v0 int32) int32 {
	t0 := v0
	t1 := m.t0[uint32(t0)].(func() int32)()
	return t1
}
