// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	table    []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.table = make([]any, 2)
	m.elements = [][]any{[]any{m._t1, m._t2}}
	copy(m.table[0:], m.elements[0])
	return m
}
func (m *Module) _t1() int32 {
	return int32(1)
}
func (m *Module) _t2() int32 {
	return int32(2)
}
func (m *Module) Xcallt(v0 int32) int32 {
	t0 := v0
	t1 := m.table[uint32(t0)].(func() int32)()
	return t1
}
