// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	elements [][]any
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.elements = [][]any{{m.f0}, {m.f0}}
	copy(m.t0[i32(0):], m.elements[1])
	return m
}
func (m *Module) f0() {
}
func (m *Module) Xdrop_passive() {
	m.elements[0] = nil
}
func (m *Module) Xinit_passive(v0 int32) {
	table_init(m.t0, m.elements[0], i32(0), i32(0), v0)
}
func (m *Module) Xdrop_active() {
	m.elements[1] = nil
}
func (m *Module) Xinit_active(v0 int32) {
	table_init(m.t0, m.elements[1], i32(0), i32(0), v0)
}

//go:nosplit
func i32(x int32) int32 { return x }

func table_init[T int32 | int64](tab, elems []any, dest, src, n T) {
	x := uint(dest)
	z := uint(src)
	y := x + uint(n)
	w := z + uint(n)
	copy(tab[x:y], elems[z:w])
}
