// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	table []any
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xget(v0 int32) any {
	t0 := v0
	t1 := m.table[uint32(t0)]
	return t1
}
func (m *Module) Xset(v0 int32, v1 any) {
	t0 := v0
	t1 := v1
	m.table[uint32(t0)] = t1
}
func (m *Module) Xgrow(v0 int32, v1 any) int32 {
	t0 := v1
	t1 := v0
	t2 := table_grow(&m.table, t0, t1, 65536)
	return t2
}
func (m *Module) Xgrow_abbrev(v0 int32, v1 any) int32 {
	t0 := v1
	t1 := v0
	t2 := table_grow(&m.table, t0, t1, 65536)
	return t2
}
func (m *Module) Xsize() int32 {
	t0 := int32(len(m.table))
	return t0
}

func table_grow(tab *[]any, val any, delta, max int32) int32 {
	buf := *tab
	len := len(buf)
	old := int32(len)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new) - len
	if new > max || add < 0 {
		return -1
	}
	buf = append(buf, make([]any, add)...)
	if val != nil {
		cpy := buf[len:]
		for i := range cpy {
			cpy[i] = val
		}
	}
	*tab = buf
	return old
}
