// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
	memory []byte
	maxMem int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 1
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	return m
}
func (m *Module) Xcopy(v0 int32, v1 int32, v2 int32) {
	t0 := v0
	t1 := v1
	t2 := v2
	memory_copy(m.memory, uint32(t0), uint32(t1), uint32(t2))
}
func (m *Module) Xload8_u(v0 int32) int32 {
	t0 := v0
	t1 := int32(m.memory[uint32(t0)])
	return t1
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	z := uint(min(uint64(src), math.MaxUint))
	c := uint(min(uint64(n), math.MaxUint))
	y := x + c
	w := z + c
	copy(mem[x:y], mem[z:w])
}

const data0 = "\xaa\xbb\xcc\xdd"
