// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32응2Eepsilon() float32 {
	var v0, v1 float32
	_, _ = v0, v1
	v0 = f32_const(1)
l0:
	{
		v1 = v0
		v0 = float32(v1 * float32(0.5))
		if float32(v0+f32_const(1)) > f32_const(1) {
			goto l0
		}
	}
	return v1
}
func (m *Module) Xf64응2Eepsilon() float64 {
	var v0, v1 float64
	_, _ = v0, v1
	v0 = f64_const(1)
l0:
	{
		v1 = v0
		v0 = float64(v1 * float64(0.5))
		if float64(v0+f64_const(1)) > f64_const(1) {
			goto l0
		}
	}
	return v1
}

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
