// Code generated by wasm2go. DO NOT EDIT.

package fib

type Module struct {
	memory []byte
}

func (m Module) Xfibonacci(v0 int32) int32 {
	var v1, v2 int32
	t0 := v0
	t1 := v0
	t3 := int32(0)
	if t1 > int32(0) {
		t3 = t0
	}
	v0 = t3
	v1 = int32(1)
	var t4 int32
l0:
	{
		t5 := v0
		var t6 int32
		if t5 != 0 {
			t7 := v0
			t8 := t7 - int32(1)
			v0 = t8
			t9 := v2
			t10 := v1
			v2 = t10
			t11 := t9 + t10
			v1 = t11
			goto l0
		} else {
			t12 := v2
			t6 = t12
		}
		t4 = t6
	}
	return t4
}
