// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       *[]any
	elements [][]any
	_module1 Xmodule1
}

func New(v0 Xmodule1) *Module {
	m := &Module{}
	m._module1 = v0
	m.t0 = v0.Xshared_table_1d64st1()
	m.elements = [][]any{{m.f0}, {m.f1}}
	copy((*m.t0)[8:], m.elements[0])
	copy((*m.t0)[9:], m.elements[1])
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xmodule1 = interface {
	Xshared_table_1d64st1() *[]any
}

func (m *Module) f0() int32 {
	return int32(69)
}
func (m *Module) f1() int32 {
	return int32(70)
}
