// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math/bits"
	"runtime"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	g0       int32
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.f19}}
	copy(m.t0[0:], m.elements[0])
	m.g0 = int32(10)
	return m
}
func (m *Module) f0() {
}
func (m *Module) Xempty() {
	{
	}
	{
	}
}
func (m *Module) Xsingular() int32 {
	{
	}
	var p0 int32
	_ = p0
	{
		p0 = int32(7)
	}
	return p0
}
func (m *Module) Xmulti() int32 {
	{
		m.f0()
		m.f0()
		m.f0()
		m.f0()
	}
	var p0 int32
	_ = p0
	{
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		p0 = int32(7)
	}
	_ = p0
	var p1 int32
	var p2 int64
	var p3 int32
	_, _, _ = p1, p2, p3
	{
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		p1, p2, p3 = int32(8), int64(7), int32(9)
	}
	_ = p3
	_ = p2
	return p1
}
func (m *Module) Xnested() int32 {
	var p0 int32
	_ = p0
	{
		{
			m.f0()
			{
			}
		}
		var p1 int32
		_ = p1
		{
			m.f0()
			p1 = int32(9)
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xdeep() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			var p2 int32
			_ = p2
			{
				var p3 int32
				_ = p3
				{
					var p4 int32
					_ = p4
					{
						var p5 int32
						_ = p5
						{
							var p6 int32
							_ = p6
							{
								var p7 int32
								_ = p7
								{
									var p8 int32
									_ = p8
									{
										var p9 int32
										_ = p9
										{
											var p10 int32
											_ = p10
											{
												var p11 int32
												_ = p11
												{
													var p12 int32
													_ = p12
													{
														var p13 int32
														_ = p13
														{
															var p14 int32
															_ = p14
															{
																var p15 int32
																_ = p15
																{
																	var p16 int32
																	_ = p16
																	{
																		var p17 int32
																		_ = p17
																		{
																			var p18 int32
																			_ = p18
																			{
																				var p19 int32
																				_ = p19
																				{
																					var p20 int32
																					_ = p20
																					{
																						var p21 int32
																						_ = p21
																						{
																							var p22 int32
																							_ = p22
																							{
																								var p23 int32
																								_ = p23
																								{
																									var p24 int32
																									_ = p24
																									{
																										var p25 int32
																										_ = p25
																										{
																											var p26 int32
																											_ = p26
																											{
																												var p27 int32
																												_ = p27
																												{
																													var p28 int32
																													_ = p28
																													{
																														var p29 int32
																														_ = p29
																														{
																															var p30 int32
																															_ = p30
																															{
																																var p31 int32
																																_ = p31
																																{
																																	var p32 int32
																																	_ = p32
																																	{
																																		var p33 int32
																																		_ = p33
																																		{
																																			var p34 int32
																																			_ = p34
																																			{
																																				var p35 int32
																																				_ = p35
																																				{
																																					var p36 int32
																																					_ = p36
																																					{
																																						var p37 int32
																																						_ = p37
																																						{
																																							m.f0()
																																							p37 = i32_const(150)
																																						}
																																						p36 = p37
																																					}
																																					p35 = p36
																																				}
																																				p34 = p35
																																			}
																																			p33 = p34
																																		}
																																		p32 = p33
																																	}
																																	p31 = p32
																																}
																																p30 = p31
																															}
																															p29 = p30
																														}
																														p28 = p29
																													}
																													p27 = p28
																												}
																												p26 = p27
																											}
																											p25 = p26
																										}
																										p24 = p25
																									}
																									p23 = p24
																								}
																								p22 = p23
																							}
																							p21 = p22
																						}
																						p20 = p21
																					}
																					p19 = p20
																				}
																				p18 = p19
																			}
																			p17 = p18
																		}
																		p16 = p17
																	}
																	p15 = p16
																}
																p14 = p15
															}
															p13 = p14
														}
														p12 = p13
													}
													p11 = p12
												}
												p10 = p11
											}
											p9 = p10
										}
										p8 = p9
									}
									p7 = p8
								}
								p6 = p7
							}
							p5 = p6
						}
						p4 = p5
					}
					p3 = p4
				}
				p2 = p3
			}
			p1 = p2
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_select_first_1p4pbiq() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := int32(2)
	if int32(3) != 0 {
		p1 = p0
	}
	return p1
}
func (m *Module) Xas_select_mid_19eybyo() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := p0
	if int32(3) != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas_select_last_ndhg92() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := int32(3)
	if p0 != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas_loop_first_liv75m() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		m.f0()
		m.f0()
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_loop_mid_1pzjrn8() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		m.f0()
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_loop_last_dr7k79() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		m.f0()
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_if_condition_mme5rn() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	if p0 != 0 {
		m.f0()
	}
}
func (m *Module) Xas_if_then_8by7gv() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
	} else {
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas_if_else_y9fza0() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		p0 = int32(2)
	} else {
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_br_if_first_11nmxnr() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		if int32(2) != 0 {
			p0 = p1
			goto l0
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_last_1dvgji4() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		if p1 != 0 {
			p0 = int32(2)
			goto l0
		}
		p0 = int32(2)
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_first_1ammix2() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		switch int32(2) {
		default:
			p0 = p1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_last_10cg6o3() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		switch p1 {
		default:
			p0 = int32(2)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) f19(v0 int32, v1 int32) int32 {
	return v0
}
func (m *Module) Xas_call_indirect_first_1kls7bs() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		t2 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(p1, int32(2))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_call_indirect_mid_1u5vulp() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		t2 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(2), p1)
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_call_indirect_last_os2e8m() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = i32_const(0)
		}
		t2 := m.t0[uint(p1)].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_store_first_1jby9fx() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	binary.LittleEndian.PutUint32(m.memory[uint32(p0):], uint32(int32(1)))
}
func (m *Module) Xas_store_last_4x4vf1() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(10)):], uint32(p0))
}
func (m *Module) Xas_memory_grow_value_7gs2mr() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := int32(memory_grow(&m.memory, int64(p0), m.maxMem))
	return t1
}
func (m *Module) f26(v0 int32) int32 {
	return v0
}
func (m *Module) Xas_call_value_go1q6u() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := m.f26(p0)
	return t1
}
func (m *Module) Xas_return_value_1wph1uy() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	return p0
}
func (m *Module) Xas_drop_operand_1m7m2py() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	_ = p0
}
func (m *Module) Xas_br_value_1sx9dl7() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas_local_set_value_1e0q6mz() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	v0 = p0
	return v0
}
func (m *Module) Xas_local_tee_value_11lf5v3() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	v0 = p0
	return v0
}
func (m *Module) Xas_global_set_value_p447yq() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	m.g0 = p0
	t1 := m.g0
	return t1
}
func (m *Module) Xas_load_operand_dz3ecr() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(p0):]))
	return t1
}
func (m *Module) Xas_unary_operand_kr3bi8() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(13)
	}
	return int32(bits.TrailingZeros32(uint32(p0)))
}
func (m *Module) Xas_binary_operand_zlxanv() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(3)
	}
	var p1 int32
	_ = p1
	{
		m.f0()
		p1 = int32(4)
	}
	return p0 * p1
}
func (m *Module) Xas_test_operand_khoiq6() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(13)
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas_compare_operand_1atwg6r() int32 {
	var p0 float32
	_ = p0
	{
		m.f0()
		p0 = float32(3)
	}
	var p1 float32
	_ = p1
	{
		m.f0()
		p1 = float32(3)
	}
	var p2 int32
	if p0 > p1 {
		p2 = 1
	}
	return p2
}
func (m *Module) Xas_binary_operands_16jzo8n() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = int32(3), int32(4)
	}
	return p0 * p1
}
func (m *Module) Xas_compare_operands_1lr1o87() int32 {
	var p0 float32
	var p1 float32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = float32(3), float32(3)
	}
	var p2 int32
	if p0 > p1 {
		p2 = 1
	}
	return p2
}
func (m *Module) Xas_mixed_operands_talftv() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = int32(3), int32(4)
	}
	return p0 * (p1 + int32(5))
}
func (m *Module) Xbreak_bare_1w8e40o() int32 {
	{
		goto l0
	}
l0:
	{
		if int32(1) != 0 {
			goto l1
		}
		panic("unreachable")
	}
l1:
	{
		switch i32_const(0) {
		default:
			goto l2
		}
	}
l2:
	{
		switch int32(1) {
		default:
			goto l3
		}
	}
l3:
	return int32(19)
}
func (m *Module) Xbreak_value_15pmn9u() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(18)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xbreak_multi_value_y8hzfm() (int32, int32, int64) {
	var p0 int32
	var p1 int32
	var p2 int64
	_, _, _ = p0, p1, p2
	{
		p0, p1, p2 = int32(18), i32_const(-18), int64(18)
		goto l0
	}
l0:
	return p0, p1, p2
}
func (m *Module) Xbreak_repeated_1htdmfz() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(18)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xbreak_inner_d2l568() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	t1 := v0
	var p0 int32
	_ = p0
	{
		var p2 int32
		_ = p2
		{
			p0 = int32(1)
			goto l0
		}
	}
l0:
	v0 = t1 + p0
	t4 := v0
	var p3 int32
	_ = p3
	{
		{
			goto l1
		}
	l1:
		p3 = int32(2)
	}
	v0 = t4 + p3
	t6 := v0
	var p5 int32
	_ = p5
	{
		p5 = int32(4)
		goto l2
	}
l2:
	v0 = t6 + p5
	t8 := v0
	var p7 int32
	_ = p7
	{
		var p9 int32
		_ = p9
		{
			p7 = int32(8)
			goto l3
		}
	}
l3:
	v0 = t8 + p7
	return v0
}
func (m *Module) Xparam() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(1) + int32(2)
		p0 = t1
	}
	return p0
}
func (m *Module) Xparams() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(1) + int32(2)
		p0 = t1
	}
	return p0
}
func (m *Module) Xparams_id_k4eonk() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		p0, p1 = int32(1), int32(2)
	}
	return p0 + p1
}
func (m *Module) Xparam_break_o3viaw() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(1) + int32(2)
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xparams_break_da59t7() int32 {
	var p0 int32
	_ = p0
	{
		t1 := int32(1) + int32(2)
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xparams_id_break_1eqx8pk() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		p0, p1 = int32(1), int32(2)
		goto l0
	}
l0:
	return p0 + p1
}
func (m *Module) Xeffects() int32 {
	var v0 int32
	_ = v0
	{
		v0 = int32(1)
		v0 = v0 * int32(3)
		v0 = v0 - int32(5)
		v0 = v0 * int32(7)
		goto l0
	}
l0:
	;
	var p0 int32
	if v0 == i32_const(-14) {
		p0 = 1
	}
	return p0
}
func (m *Module) Xtype_use_ka4o2i() {
	{
	}
	var p0 int32
	_ = p0
	{
		p0 = i32_const(0)
	}
	{
		_ = p0
	}
	var p1 int32
	var p2 float64
	var p3 int32
	_, _, _ = p1, p2, p3
	{
		p1, p2, p3 = i32_const(0), f64_const(0), i32_const(0)
	}
	_ = p3
	_ = p2
	_ = p1
	var p4 int32
	_ = p4
	{
		p4 = i32_const(0)
	}
	{
		_ = p4
	}
	var p5 int32
	var p6 float64
	var p7 int32
	_, _, _ = p5, p6, p7
	{
		p5, p6, p7 = i32_const(0), f64_const(0), i32_const(0)
	}
	_ = p7
	_ = p6
	_ = p5
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
