// Code generated by wasm2go. DO NOT EDIT.

package stack

type Module struct {
	memory []byte
}

func (m Module) f0(v0 int32, v1 int32) int32 {
	t0 := v0
	return t0 - v1
}
func (m Module) Xstack_func_call() int32 {
	t0 := m.f0(int32(91), int32(23))
	return t0
}
func (m Module) Xgreater(v0 int32, v1 int32) int32 {
	t0 := v0
	var t3 int32
	if t0 > v1 {
		t3 = int32(1)
	} else {
		t3 = int32(0)
	}
	return t3
}
func (m Module) Xtwo_a_plus_b(v0 int32, v1 int32) int32 {
	var v2 int32
	t0 := v1
	t1 := v0
	v2 = t1
	t2 := t0 + t1
	return t2 + v2
}
func (m Module) Xtee_for_two(v0 int32, v1 int32) (int32, int32) {
	var v2 int32
	t0 := v0
	t1 := v0
	t3 := t1 + v1
	v2 = t3
	t4 := t0 + t3
	return t4, v2
}
