// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_no_fold_mul_div_s_11irf8t(v0 int32) int32 {
	t0 := i32_div_s(v0*int32(6), int32(6))
	return t0
}
func (m *Module) Xi32_no_fold_mul_div_u_18u8xz9(v0 int32) int32 {
	t0 := int32(uint32(v0*int32(6)) / uint32(int32(6)))
	return t0
}
func (m *Module) Xi64_no_fold_mul_div_s_1w7q57p(v0 int64) int64 {
	t0 := i64_div_s(v0*int64(6), int64(6))
	return t0
}
func (m *Module) Xi64_no_fold_mul_div_u_1mobitp(v0 int64) int64 {
	t0 := int64(uint64(v0*int64(6)) / uint64(int64(6)))
	return t0
}

//go:nosplit
func i32_div_s(x, y int32) int32 {
	if y == -1 && x == math.MinInt32 {
		panic("integer overflow")
	}
	return x / y
}

//go:nosplit
func i64_div_s(x, y int64) int64 {
	if y == -1 && x == math.MinInt64 {
		panic("integer overflow")
	}
	return x / y
}
