// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := new(Module)
	return m
}
func (m *Module) Xclassify(v0 int32) int32 {
	var v1 int32
	switch v0 {
	default:
		goto l3
	case 0:
		v1 = v1 + i32(1)
		fallthrough
	case 1:
		v1 = v1 + i32(10)
		if v1 == i32(11) {
			goto l3
		}
		fallthrough
	case 2:
		v1 = v1 + i32(100)
	}
l3:
	return v1 + i32(1000)
}

//go:nosplit
func i32(x int32) int32 { return x }
