// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xtype_local_i32_cmmy8t() int32 {
	var v0 int32
	_ = v0
	return v0
}
func (m *Module) Xtype_local_i64_nvg71a() int64 {
	var v0 int64
	_ = v0
	return v0
}
func (m *Module) Xtype_local_f32_qy93zl() float32 {
	var v0 float32
	_ = v0
	return v0
}
func (m *Module) Xtype_local_f64_7eeh4i() float64 {
	var v0 float64
	_ = v0
	return v0
}
func (m *Module) Xtype_param_i32_vcyvx(v0 int32) int32 {
	return v0
}
func (m *Module) Xtype_param_i64_xhaz1a(v0 int64) int64 {
	return v0
}
func (m *Module) Xtype_param_f32_m27rch(v0 float32) float32 {
	return v0
}
func (m *Module) Xtype_param_f64_efvqeq(v0 float64) float64 {
	return v0
}
func (m *Module) Xtype_mixed_1gr773l(v0 int64, v1 float32, v2 float64, v3 int32, v4 int32) {
	var v5 float32
	var v6, v7 int64
	var v8 float64
	_, _, _, _ = v5, v6, v7, v8
	var p0 int32
	if v0 == 0 {
		p0 = 1
	}
	_ = p0
	_ = -v1
	_ = -v2
	var p1 int32
	if v3 == 0 {
		p1 = 1
	}
	_ = p1
	var p2 int32
	if v4 == 0 {
		p2 = 1
	}
	_ = p2
	_ = -v5
	var p3 int32
	if v6 == 0 {
		p3 = 1
	}
	_ = p3
	var p4 int32
	if v7 == 0 {
		p4 = 1
	}
	_ = p4
	_ = -v8
}
func (m *Module) Xread(v0 int64, v1 float32, v2 float64, v3 int32, v4 int32) float64 {
	var v5 float32
	var v6, v7 int64
	var v8 float64
	_, _, _, _ = v5, v6, v7, v8
	v5 = float32(5.5)
	v6 = i64(6)
	v8 = float64(8)
	return float64(float64(uint64(v0)) + float64(float64(v1)+float64(v2+float64(float64(uint32(v3))+float64(float64(v4)+float64(float64(v5)+float64(float64(uint64(v6))+float64(float64(uint64(v7))+v8))))))))
}
func (m *Module) Xas_block_value_pg8qbp(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
	}
	return p0
}
func (m *Module) Xas_loop_value_amjtft(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
	}
	return p0
}
func (m *Module) Xas_br_value_1sx9dl7(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_value_1tlgvkk(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if i32(1) != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_value_cond_pzz0yu(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if v0 != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_value_1ic2jxx(v0 int32) int32 {
	{
		{
			{
				switch v0 {
				case 0:
					goto l0
				case 1:
					goto l1
				default:
					goto l2
				}
			}
		l0:
			return i32(1)
		}
	l1:
		return i32(2)
	}
l2:
	return i32(3)
}
func (m *Module) Xas_return_value_1wph1uy(v0 int32) int32 {
	return v0
}
func (m *Module) Xas_if_then_8by7gv(v0 int32) int32 {
	var p0 int32
	_ = p0
	if v0 != 0 {
		t1 := v0
		p0 = t1
	} else {
		p0 = i32(0)
	}
	return p0
}
func (m *Module) Xas_if_else_y9fza0(v0 int32) int32 {
	var p0 int32
	_ = p0
	if v0 != 0 {
		p0 = i32(1)
	} else {
		t1 := v0
		p0 = t1
	}
	return p0
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }
