// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_mul_sqrts_1gbd1mb(v0 float32, v1 float32) float32 {
	return float32(float32(math.Sqrt(float64(v0))) * float32(math.Sqrt(float64(v1))))
}
func (m *Module) Xf64_no_fold_mul_sqrts_1la14sb(v0 float64, v1 float64) float64 {
	return float64(math.Sqrt(v0) * math.Sqrt(v1))
}
