// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) Xas_block_value_pg8qbp() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
	}
}
func (m *Module) Xas_loop_value_amjtft() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
	}
}
func (m *Module) Xas_br_value_1sx9dl7() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
		goto l0
	}
l0:
}
func (m *Module) Xas_br_if_value_1tlgvkk() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
		if int32(1) != 0 {
			goto l0
		}
	}
l0:
}
func (m *Module) Xas_br_if_value_cond_pzz0yu() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
		if int32(6) != 0 {
			goto l0
		}
	}
l0:
}
func (m *Module) Xas_br_table_value_1ic2jxx() {
	{
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
		switch int32(1) {
		default:
			goto l0
		}
	}
l0:
}
func (m *Module) Xas_return_value_1wph1uy() {
	binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
	return
}
func (m *Module) Xas_if_then_8by7gv() {
	if int32(1) != 0 {
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
	}
}
func (m *Module) Xas_if_else_y9fza0() {
	if i32_const(0) != 0 {
	} else {
		binary.LittleEndian.PutUint32(m.memory[uint32(i32_const(0)):], uint32(int32(1)))
	}
}

//go:nosplit
func i32_const(x int32) int32 { return x }
