// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 1
	m.memory = make([]byte, 65536)
	copy(m.memory[0:], data0)
	return m
}
func (m *Module) Xmemsize() int32 {
	t0 := int32(len(m.memory) >> 16)
	return t0
}

const data0 = "x"
