// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
	table    []any
	elements [][]any
	memory   []byte
	maxMem   int32
	g0       float32
}

func New() *Module {
	m := &Module{}
	m.table = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{[]any{m.f1}}
	copy(m.table[0:], m.elements[0])
	m.g0 = f32_const(0)
	return m
}
func (m *Module) f0() {
}
func (m *Module) f1(v0 int32, v1 int32, v2 int32) {
}
func (m *Module) Xtype_i32() int32 {
	panic("unreachable")
}
func (m *Module) Xtype_i64() int64 {
	panic("unreachable")
}
func (m *Module) Xtype_f32() float32 {
	panic("unreachable")
}
func (m *Module) Xtype_f64() float64 {
	panic("unreachable")
}
func (m *Module) Xas_func_first() int32 {
	panic("unreachable")
}
func (m *Module) Xas_func_mid() int32 {
	m.f0()
	panic("unreachable")
}
func (m *Module) Xas_func_last() {
	m.f0()
	panic("unreachable")
}
func (m *Module) Xas_func_value() int32 {
	m.f0()
	panic("unreachable")
}
func (m *Module) Xas_block_first() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_block_mid() int32 {
	var t0 int32
	_ = t0
	{
		m.f0()
		panic("unreachable")
	}
}
func (m *Module) Xas_block_last() {
	{
		m.f0()
		panic("unreachable")
	}
}
func (m *Module) Xas_block_value() int32 {
	var t0 int32
	_ = t0
	{
		m.f0()
		panic("unreachable")
	}
}
func (m *Module) Xas_block_broke() int32 {
	var t0 int32
	_ = t0
	{
		m.f0()
		t0 = int32(1)
		goto l0
	}
l0:
	return t0
}
func (m *Module) Xas_loop_first() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_loop_mid() int32 {
	var t0 int32
	_ = t0
	{
		m.f0()
		panic("unreachable")
	}
}
func (m *Module) Xas_loop_last() {
	{
		m.f0()
		panic("unreachable")
	}
}
func (m *Module) Xas_loop_broke() int32 {
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			m.f0()
			t0 = int32(1)
			goto l0
		}
	}
l0:
	return t0
}
func (m *Module) Xas_br_value() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_if_cond() {
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_if_value() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_if_value_cond() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_table_index() {
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_table_value() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_table_value_2() int32 {
	var t0 int32
	_ = t0
	{
		var t1 int32
		_ = t1
		{
			panic("unreachable")
		}
	}
}
func (m *Module) Xas_br_table_value_index() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_br_table_value_and_index() int32 {
	var t0 int32
	_ = t0
	{
		panic("unreachable")
	}
}
func (m *Module) Xas_return_value() int64 {
	panic("unreachable")
}
func (m *Module) Xas_if_cond() int32 {
	panic("unreachable")
}
func (m *Module) Xas_if_then(v0 int32, v1 int32) int32 {
	t0 := v0
	var t1 int32
	_ = t1
	if t0 != 0 {
		panic("unreachable")
	} else {
		t2 := v1
		t1 = t2
	}
	return t1
}
func (m *Module) Xas_if_else(v0 int32, v1 int32) int32 {
	t0 := v0
	var t1 int32
	_ = t1
	if t0 != 0 {
		t2 := v1
		t1 = t2
	} else {
		panic("unreachable")
	}
	return t1
}
func (m *Module) Xas_if_then_no_else(v0 int32, v1 int32) int32 {
	t0 := v0
	if t0 != 0 {
		panic("unreachable")
	}
	t1 := v1
	return t1
}
func (m *Module) Xas_select_first(v0 int32, v1 int32) int32 {
	panic("unreachable")
}
func (m *Module) Xas_select_second(v0 int32, v1 int32) int32 {
	_ = v0
	panic("unreachable")
}
func (m *Module) Xas_select_cond() int32 {
	panic("unreachable")
}
func (m *Module) Xas_call_first() {
	panic("unreachable")
}
func (m *Module) Xas_call_mid() {
	panic("unreachable")
}
func (m *Module) Xas_call_last() {
	panic("unreachable")
}
func (m *Module) Xas_call_indirect_func() {
	panic("unreachable")
}
func (m *Module) Xas_call_indirect_first() {
	panic("unreachable")
}
func (m *Module) Xas_call_indirect_mid() {
	panic("unreachable")
}
func (m *Module) Xas_call_indirect_last() {
	panic("unreachable")
}
func (m *Module) Xas_local_set_value() {
	var v0 float32
	_ = v0
	panic("unreachable")
}
func (m *Module) Xas_local_tee_value() float32 {
	var v0 float32
	_ = v0
	panic("unreachable")
}
func (m *Module) Xas_global_set_value() float32 {
	panic("unreachable")
}
func (m *Module) Xas_load_address() float32 {
	panic("unreachable")
}
func (m *Module) Xas_loadN_address() int64 {
	panic("unreachable")
}
func (m *Module) Xas_store_address() {
	panic("unreachable")
}
func (m *Module) Xas_store_value() {
	panic("unreachable")
}
func (m *Module) Xas_storeN_address() {
	panic("unreachable")
}
func (m *Module) Xas_storeN_value() {
	panic("unreachable")
}
func (m *Module) Xas_unary_operand() float32 {
	panic("unreachable")
}
func (m *Module) Xas_binary_left() int32 {
	panic("unreachable")
}
func (m *Module) Xas_binary_right() int64 {
	panic("unreachable")
}
func (m *Module) Xas_test_operand() int32 {
	panic("unreachable")
}
func (m *Module) Xas_compare_left() int32 {
	panic("unreachable")
}
func (m *Module) Xas_compare_right() int32 {
	panic("unreachable")
}
func (m *Module) Xas_convert_operand() int32 {
	panic("unreachable")
}
func (m *Module) Xas_memory_grow_size() int32 {
	panic("unreachable")
}

func i32_const(x int32) int32 { return x }

func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

func memory_grow(mem *[]byte, delta, max int32) int32 {
	buf := *mem
	len := len(buf)
	old := int32(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
