// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := &Module{}
	m.maxMem = 281474976710656
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) f0() int64 {
	t0 := int64(len(m.memory) >> 16)
	t1 := t0 * i64_const(65536)
	return t1
}
func (m *Module) Xstore(v0 int64, v1 int32) {
	t0 := m.f0()
	t1 := v0
	t2 := t0 + t1
	t3 := v1
	binary.LittleEndian.PutUint32(m.memory[t2:], uint32(t3))
}
func (m *Module) Xload(v0 int64) int32 {
	t0 := m.f0()
	t1 := v0
	t2 := t0 + t1
	t3 := int32(binary.LittleEndian.Uint32(m.memory[t2:]))
	return t3
}
func (m *Module) Xmemory_grow(v0 int64) int64 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}

//go:nosplit
func i64_const(x int64) int64 { return x }

func memory_grow[T int | int32 | int64](mem *[]byte, delta, max T) T {
	buf := *mem
	len := len(buf)
	old := T(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
