// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi64_no_fold_wrap_extend_s(v0 int64) int64 {
	return int64(int32(v0))
}
