// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xno_dce_i32_rem_s(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	t2 := t0 % t1
	_ = t2
}
func (m *Module) Xno_dce_i32_rem_u(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	t2 := int32(uint32(t0) % uint32(t1))
	_ = t2
}
func (m *Module) Xno_dce_i64_rem_s(v0 int64, v1 int64) {
	t0 := v0
	t1 := v1
	t2 := t0 % t1
	_ = t2
}
func (m *Module) Xno_dce_i64_rem_u(v0 int64, v1 int64) {
	t0 := v0
	t1 := v1
	t2 := int64(uint64(t0) % uint64(t1))
	_ = t2
}
