// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_sqrt_square(v0 float32) float32 {
	t0 := v0
	t1 := v0
	t2 := float32(t0 * t1)
	t3 := float32(math.Sqrt(float64(t2)))
	return t3
}
func (m *Module) Xf64_no_fold_sqrt_square(v0 float64) float64 {
	t0 := v0
	t1 := v0
	t2 := float64(t0 * t1)
	t3 := math.Sqrt(t2)
	return t3
}
