// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_lt_if_1vxdmyp(v0 float32, v1 float32) float32 {
	var p0 float32
	_ = p0
	if v0 < v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf32_no_fold_le_if_1hj9890(v0 float32, v1 float32) float32 {
	var p0 float32
	_ = p0
	if v0 <= v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf32_no_fold_gt_if_xpthb8(v0 float32, v1 float32) float32 {
	var p0 float32
	_ = p0
	if v0 > v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf32_no_fold_ge_if_ljlkkh(v0 float32, v1 float32) float32 {
	var p0 float32
	_ = p0
	if v0 >= v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf64_no_fold_lt_if_15327vn(v0 float64, v1 float64) float64 {
	var p0 float64
	_ = p0
	if v0 < v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf64_no_fold_le_if_18g7jza(v0 float64, v1 float64) float64 {
	var p0 float64
	_ = p0
	if v0 <= v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf64_no_fold_gt_if_70g6bq(v0 float64, v1 float64) float64 {
	var p0 float64
	_ = p0
	if v0 > v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
func (m *Module) Xf64_no_fold_ge_if_clik5f(v0 float64, v1 float64) float64 {
	var p0 float64
	_ = p0
	if v0 >= v1 {
		t1 := v0
		p0 = t1
	} else {
		t2 := v1
		p0 = t2
	}
	return p0
}
