// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math/bits"
	"runtime"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int32
	g0       int32
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.f16}}
	copy(m.t0[0:], m.elements[0])
	m.g0 = i32_const(0)
	return m
}
func (m *Module) f0() {
}
func (m *Module) Xempty() {
	{
	}
	{
	}
}
func (m *Module) Xsingular() int32 {
	{
	}
	var p0 int32
	_ = p0
	{
		p0 = int32(7)
	}
	return p0
}
func (m *Module) Xmulti() int32 {
	{
		m.f0()
		m.f0()
		m.f0()
		m.f0()
	}
	var p0 int32
	_ = p0
	{
		m.f0()
		m.f0()
		m.f0()
		p0 = int32(8)
	}
	_ = p0
	var p1 int32
	var p2 int64
	var p3 int32
	_, _, _ = p1, p2, p3
	{
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		m.f0()
		p1, p2, p3 = int32(8), int64(7), int32(9)
	}
	_ = p3
	_ = p2
	return p1
}
func (m *Module) Xnested() int32 {
	var p0 int32
	_ = p0
	{
		{
			m.f0()
			{
			}
		}
		var p1 int32
		_ = p1
		{
			m.f0()
			p1 = int32(9)
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xdeep() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			var p2 int32
			_ = p2
			{
				var p3 int32
				_ = p3
				{
					var p4 int32
					_ = p4
					{
						var p5 int32
						_ = p5
						{
							var p6 int32
							_ = p6
							{
								var p7 int32
								_ = p7
								{
									var p8 int32
									_ = p8
									{
										var p9 int32
										_ = p9
										{
											var p10 int32
											_ = p10
											{
												var p11 int32
												_ = p11
												{
													var p12 int32
													_ = p12
													{
														var p13 int32
														_ = p13
														{
															var p14 int32
															_ = p14
															{
																var p15 int32
																_ = p15
																{
																	var p16 int32
																	_ = p16
																	{
																		var p17 int32
																		_ = p17
																		{
																			var p18 int32
																			_ = p18
																			{
																				var p19 int32
																				_ = p19
																				{
																					var p20 int32
																					_ = p20
																					{
																						var p21 int32
																						_ = p21
																						{
																							var p22 int32
																							_ = p22
																							{
																								var p23 int32
																								_ = p23
																								{
																									var p24 int32
																									_ = p24
																									{
																										var p25 int32
																										_ = p25
																										{
																											var p26 int32
																											_ = p26
																											{
																												var p27 int32
																												_ = p27
																												{
																													var p28 int32
																													_ = p28
																													{
																														var p29 int32
																														_ = p29
																														{
																															var p30 int32
																															_ = p30
																															{
																																var p31 int32
																																_ = p31
																																{
																																	var p32 int32
																																	_ = p32
																																	{
																																		var p33 int32
																																		_ = p33
																																		{
																																			var p34 int32
																																			_ = p34
																																			{
																																				var p35 int32
																																				_ = p35
																																				{
																																					var p36 int32
																																					_ = p36
																																					{
																																						var p37 int32
																																						_ = p37
																																						{
																																							var p38 int32
																																							_ = p38
																																							{
																																								var p39 int32
																																								_ = p39
																																								{
																																									m.f0()
																																									p39 = i32_const(150)
																																								}
																																								p38 = p39
																																							}
																																							p37 = p38
																																						}
																																						p36 = p37
																																					}
																																					p35 = p36
																																				}
																																				p34 = p35
																																			}
																																			p33 = p34
																																		}
																																		p32 = p33
																																	}
																																	p31 = p32
																																}
																																p30 = p31
																															}
																															p29 = p30
																														}
																														p28 = p29
																													}
																													p27 = p28
																												}
																												p26 = p27
																											}
																											p25 = p26
																										}
																										p24 = p25
																									}
																									p23 = p24
																								}
																								p22 = p23
																							}
																							p21 = p22
																						}
																						p20 = p21
																					}
																					p19 = p20
																				}
																				p18 = p19
																			}
																			p17 = p18
																		}
																		p16 = p17
																	}
																	p15 = p16
																}
																p14 = p15
															}
															p13 = p14
														}
														p12 = p13
													}
													p11 = p12
												}
												p10 = p11
											}
											p9 = p10
										}
										p8 = p9
									}
									p7 = p8
								}
								p6 = p7
							}
							p5 = p6
						}
						p4 = p5
					}
					p3 = p4
				}
				p2 = p3
			}
			p1 = p2
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_select_first() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := int32(2)
	if int32(3) != 0 {
		p1 = p0
	}
	return p1
}
func (m *Module) Xas_select_mid() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := p0
	if int32(3) != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas_select_last() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	p1 := int32(3)
	if p0 != 0 {
		p1 = int32(2)
	}
	return p1
}
func (m *Module) Xas_if_condition() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	if p0 != 0 {
		m.f0()
	}
}
func (m *Module) Xas_if_then() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
	} else {
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas_if_else() int32 {
	var p0 int32
	_ = p0
	if int32(1) != 0 {
		p0 = int32(2)
	} else {
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
	}
	return p0
}
func (m *Module) Xas_br_if_first() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
		if int32(2) != 0 {
			goto l0
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xas_br_if_last() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = int32(2)
		if p1 != 0 {
			goto l0
		}
		p0 = int32(2)
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_first() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
		switch int32(2) {
		default:
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas_br_table_last() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = int32(2)
		switch p1 {
		default:
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) f16(v0 int32, v1 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_call_indirect_first() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		t2 := m.t0[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(p1, int32(2))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_call_indirect_mid() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		t2 := m.t0[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(2), p1)
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_call_indirect_last() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = i32_const(0)
		}
		t2 := m.t0[uint32(p1)].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t2
	}
	return p0
}
func (m *Module) Xas_store_first() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	binary.LittleEndian.PutUint32(m.memory[uint32(p0):], uint32(int32(1)))
}
func (m *Module) Xas_store_last() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	binary.LittleEndian.PutUint32(m.memory[uint32(int32(10)):], uint32(p0))
}
func (m *Module) Xas_memory_grow_value() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := memory_grow(&m.memory, p0, m.maxMem)
	return t1
}
func (m *Module) f23(v0 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_call_value() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := m.f23(p0)
	return t1
}
func (m *Module) Xas_return_value() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	return p0
}
func (m *Module) Xas_drop_operand() {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	_ = p0
}
func (m *Module) Xas_br_value() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p1 = int32(1)
		}
		p0 = p1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas_local_set_value() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	v0 = p0
	t1 := v0
	return t1
}
func (m *Module) Xas_local_tee_value() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	v0 = p0
	return p0
}
func (m *Module) Xas_global_set_value() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	m.g0 = p0
	t1 := m.g0
	return t1
}
func (m *Module) Xas_load_operand() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(1)
	}
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(p0):]))
	return t1
}
func (m *Module) Xas_unary_operand() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(13)
	}
	t1 := int32(bits.TrailingZeros32(uint32(p0)))
	return t1
}
func (m *Module) Xas_binary_operand() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(3)
	}
	var p1 int32
	_ = p1
	{
		m.f0()
		p1 = int32(4)
	}
	t2 := p0 * p1
	return t2
}
func (m *Module) Xas_test_operand() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(13)
	}
	var p1 int32
	if p0 == 0 {
		p1 = 1
	}
	return p1
}
func (m *Module) Xas_compare_operand() int32 {
	var p0 float32
	_ = p0
	{
		m.f0()
		p0 = float32(3)
	}
	var p1 float32
	_ = p1
	{
		m.f0()
		p1 = float32(3)
	}
	var p2 int32
	if p0 > p1 {
		p2 = 1
	}
	return p2
}
func (m *Module) Xas_binary_operands() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = int32(3), int32(4)
	}
	t2 := p0 * p1
	return t2
}
func (m *Module) Xas_compare_operands() int32 {
	var p0 float32
	var p1 float32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = float32(3), float32(3)
	}
	var p2 int32
	if p0 > p1 {
		p2 = 1
	}
	return p2
}
func (m *Module) Xas_mixed_operands() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	{
		m.f0()
		m.f0()
		p0, p1 = int32(3), int32(4)
	}
	t2 := p1 + int32(5)
	t3 := p0 * t2
	return t3
}
func (m *Module) Xbreak_bare() int32 {
	{
		{
			goto l0
		}
	}
l0:
	{
		{
			if int32(1) != 0 {
				goto l1
			}
			panic("unreachable")
		}
	}
l1:
	{
		{
			switch i32_const(0) {
			default:
				goto l2
			}
		}
	}
l2:
	{
		{
			switch int32(1) {
			default:
				goto l3
			}
		}
	}
l3:
	return int32(19)
}
func (m *Module) Xbreak_value() int32 {
	var p0 int32
	_ = p0
	{
		_ = i32_const(0)
		{
			{
				p0 = int32(18)
				goto l0
			}
		}
	}
l0:
	return p0
}
func (m *Module) Xbreak_multi_value() (int32, int32, int64) {
	var p0 int32
	var p1 int32
	var p2 int64
	_, _, _ = p0, p1, p2
	{
		_, _, _ = i32_const(0), i32_const(0), i64_const(0)
		{
			{
				p0, p1, p2 = int32(18), i32_const(-18), int64(18)
				goto l0
			}
		}
	}
l0:
	return p0, p1, p2
}
func (m *Module) Xbreak_repeated() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p0 = int32(18)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xbreak_inner() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	t0 := v0
	var p1 int32
	_ = p1
	{
		var p2 int32
		_ = p2
		{
			var p3 int32
			_ = p3
			{
				p1 = int32(1)
				goto l0
			}
		}
	}
l0:
	t4 := t0 + p1
	v0 = t4
	t5 := v0
	var p6 int32
	_ = p6
	{
		var p7 int32
		_ = p7
		{
			var p8 int32
			_ = p8
			{
				p6 = int32(2)
				goto l1
			}
		}
	}
l1:
	t9 := t5 + p6
	v0 = t9
	t10 := v0
	var p11 int32
	_ = p11
	{
		var p12 int32
		_ = p12
		{
			var p13 int32
			_ = p13
			{
				var p14 int32
				_ = p14
				{
					p13 = int32(4)
					goto l2
				}
			}
		l2:
			p12 = p13
		}
		p11 = p12
	}
	t15 := t10 + p11
	v0 = t15
	t16 := v0
	var p17 int32
	_ = p17
	{
		var p18 int32
		_ = p18
		{
			p17 = int32(8)
			goto l3
		}
	}
l3:
	t19 := t16 + p17
	v0 = t19
	t20 := v0
	var p21 int32
	_ = p21
	{
		var p22 int32
		_ = p22
		{
			var p23 int32
			_ = p23
			{
				p21 = int32(16)
				goto l4
			}
		}
	}
l4:
	t24 := t20 + p21
	v0 = t24
	t25 := v0
	return t25
}
func (m *Module) Xcont_inner() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	_ = v0
	var p1 int32
	_ = p1
l0:
	{
		var p2 int32
		_ = p2
		{
			goto l0
		}
	}
}
func (m *Module) Xparam() int32 {
	var p0 int32
	_ = p0
	p1 := int32(1)
	{
		t2 := p1 + int32(2)
		p0 = t2
	}
	return p0
}
func (m *Module) Xparams() int32 {
	var p0 int32
	_ = p0
	p2, p1 := int32(1), int32(2)
	{
		t3 := p2 + p1
		p0 = t3
	}
	return p0
}
func (m *Module) Xparams_id() int32 {
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	p3, p2 := int32(1), int32(2)
	{
		p0, p1 = p3, p2
	}
	t4 := p0 + p1
	return t4
}
func (m *Module) Xparam_break() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	p1 := int32(1)
l0:
	{
		t2 := p1 + int32(4)
		v0 = t2
		t3 := v0
		p1 = t2
		if uint32(t3) < uint32(int32(10)) {
			goto l0
		}
		p0 = t2
	}
	return p0
}
func (m *Module) Xparams_break() int32 {
	var v0 int32
	_ = v0
	var p0 int32
	_ = p0
	p2, p1 := int32(1), int32(2)
l0:
	{
		t3 := p2 + p1
		v0 = t3
		t4 := v0
		p2, p1 = t3, int32(3)
		if uint32(t4) < uint32(int32(10)) {
			goto l0
		}
		_ = int32(3)
		p0 = t3
	}
	return p0
}
func (m *Module) Xparams_id_break() int32 {
	var v0 int32
	_ = v0
	v0 = i32_const(0)
	var p0 int32
	var p1 int32
	_, _ = p0, p1
	p3, p2 := int32(1), int32(2)
l0:
	{
		t4 := v0
		t5 := t4 + int32(1)
		v0 = t5
		t6 := v0
		if uint32(t6) < uint32(int32(10)) {
			goto l0
		}
		p0, p1 = p3, p2
	}
	t8 := p0 + p1
	return t8
}
func (m *Module) Xeffects() int32 {
	var v0 int32
	_ = v0
	{
		{
			v0 = int32(1)
			t0 := v0
			t1 := t0 * int32(3)
			v0 = t1
			t2 := v0
			t3 := t2 - int32(5)
			v0 = t3
			t4 := v0
			t5 := t4 * int32(7)
			v0 = t5
			goto l0
		}
	}
l0:
	t6 := v0
	var p7 int32
	if t6 == i32_const(-14) {
		p7 = 1
	}
	return p7
}
func (m *Module) Xwhile(v0 int64) int64 {
	var v1 int64
	_ = v1
	v1 = int64(1)
	{
	l1:
		{
			t0 := v0
			if t0 == 0 {
				goto l0
			}
			t2 := v0
			t3 := v1
			t4 := t2 * t3
			v1 = t4
			t5 := v0
			t6 := t5 - int64(1)
			v0 = t6
			goto l1
		}
	}
l0:
	t7 := v1
	return t7
}
func (m *Module) Xfor(v0 int64) int64 {
	var v1, v2 int64
	_, _ = v1, v2
	v1 = int64(1)
	v2 = int64(2)
	{
	l1:
		{
			t0 := v2
			t1 := v0
			if uint64(t0) > uint64(t1) {
				goto l0
			}
			t3 := v1
			t4 := v2
			t5 := t3 * t4
			v1 = t5
			t6 := v2
			t7 := t6 + int64(1)
			v2 = t7
			goto l1
		}
	}
l0:
	t8 := v1
	return t8
}
func (m *Module) Xnesting(v0 float32, v1 float32) float32 {
	var v2, v3 float32
	_, _ = v2, v3
	{
	l3:
		{
			t0 := v0
			if t0 == f32_const(0) {
				goto l0
			}
			t2 := v1
			v2 = t2
			{
			l2:
				{
					t3 := v2
					if t3 == f32_const(0) {
						goto l1
					}
					t5 := v2
					if t5 < f32_const(0) {
						goto l0
					}
					t7 := v3
					t8 := v2
					t9 := float32(t7 + t8)
					v3 = t9
					t10 := v2
					t11 := float32(t10 - float32(2))
					v2 = t11
					goto l2
				}
			}
		l1:
			t12 := v3
			t13 := v0
			t14 := float32(t12 / t13)
			v3 = t14
			t15 := v0
			t16 := float32(t15 - f32_const(1))
			v0 = t16
			goto l3
		}
	}
l0:
	t17 := v3
	return t17
}
func (m *Module) Xtype_use() {
	{
	}
	var p0 int32
	_ = p0
	{
		p0 = i32_const(0)
	}
	p1 := p0
	{
		_ = p1
	}
	var p2 int32
	var p3 float64
	var p4 int32
	_, _, _ = p2, p3, p4
	p7, p6, p5 := i32_const(0), f64_const(0), i32_const(0)
	{
		p2, p3, p4 = p7, p6, p5
	}
	_ = p4
	_ = p3
	_ = p2
	var p8 int32
	_ = p8
	{
		p8 = i32_const(0)
	}
	p9 := p8
	{
		_ = p9
	}
	var p10 int32
	var p11 float64
	var p12 int32
	_, _, _ = p10, p11, p12
	p15, p14, p13 := i32_const(0), f64_const(0), i32_const(0)
	{
		p10, p11, p12 = p15, p14, p13
	}
	_ = p12
	_ = p11
	_ = p10
}
func (m *Module) Xbr_implicit_drop() int32 {
	var v0 int32
	_ = v0
l0:
	{
		t0 := v0
		t1 := t0 + int32(1)
		v0 = t1
		t2 := v0
		if t2 < int32(10) {
			goto l0
		}
		_ = int32(2)
	}
	return int32(1)
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func i64_const(x int64) int64 { return x }

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}

func memory_grow(mem *[]byte, delta, max int32) int32 {
	buf := *mem
	len := len(buf)
	old := int32(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
