// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32_no_fold_rem_s_2_k5g92h(v0 int32) int32 {
	t0 := v0 % int32(2)
	return t0
}
func (m *Module) Xi64_no_fold_rem_s_2_1h8ecm5(v0 int64) int64 {
	t0 := v0 % int64(2)
	return t0
}
