// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	table []any
}

func New() *Module {
	m := &Module{}
	m.table = make([]any, 10)
	return m
}
func (m *Module) Xfill(v0 int32, v1 any, v2 int32) {
	t0 := v0
	t1 := v1
	t2 := v2
	table_fill(m.table, t0, t1, t2)
}
func (m *Module) Xfill_abbrev(v0 int32, v1 any, v2 int32) {
	t0 := v0
	t1 := v1
	t2 := v2
	table_fill(m.table, t0, t1, t2)
}
func (m *Module) Xget(v0 int32) any {
	t0 := v0
	t1 := m.table[uint32(t0)]
	return t1
}

func table_fill(tab []any, dest int32, val any, n int32) {
	x := uint(uint32(dest))
	y := x + uint(uint32(n))
	buf := tab[x:y]
	if val == nil {
		clear(buf)
		return
	}
	for i := range buf {
		buf[i] = val
	}
}
