// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_no_fold_to_hypot(v0 float32, v1 float32) float32 {
	t0 := v0
	t1 := v0
	t2 := float32(t0 * t1)
	t3 := v1
	t4 := v1
	t5 := float32(t3 * t4)
	t6 := float32(t2 + t5)
	t7 := float32(math.Sqrt(float64(t6)))
	return t7
}
func (m *Module) Xf64_no_fold_to_hypot(v0 float64, v1 float64) float64 {
	t0 := v0
	t1 := v0
	t2 := float64(t0 * t1)
	t3 := v1
	t4 := v1
	t5 := float64(t3 * t4)
	t6 := float64(t2 + t5)
	t7 := math.Sqrt(t6)
	return t7
}
