// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xcalculate() float32 {
	var v0, v1, v2, v3, v4 float32
	_, _, _, _, _ = v0, v1, v2, v3, v4
	v0 = float32(156.25)
	v1 = float32(208.33333)
	v2 = float32(1.779513)
	v3 = float32(float32(-v1*v0) / float32(float32(v0*v2)-v1))
	v4 = float32(float32(-v1*v0) / float32(float32(v0*v2)-v1))
	{
		if v3 == v4 {
			goto l0
		}
		panic("unreachable")
	}
l0:
	return v4
}
