// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xllvm_pr26746(v0 float32) float32 {
	t0 := v0
	t1 := float32(math.Float32frombits(2147483648) - t0)
	t2 := float32(float32(0) - t1)
	return t2
}
