// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0 []any
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xget_t64_1rlwded(v0 int64) any {
	t0 := m.t0[v0]
	return t0
}
func (m *Module) Xset_t64_1p6ozhe(v0 int64, v1 any) {
	m.t0[v0] = v1
}
func (m *Module) Xgrow_t64_17oobgq(v0 int64, v1 any) int64 {
	t0 := table_grow(&m.t0, v1, v0, 281474976710656)
	return t0
}
func (m *Module) Xsize_t64_dhqhet() int64 {
	t0 := int64(len(m.t0))
	return t0
}

func table_grow[T int32 | int64](tab *[]any, val any, delta, max T) T {
	buf := *tab
	len := len(buf)
	old := T(len)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new) - len
	if new > max || add < 0 {
		return -1
	}
	buf = append(buf, make([]any, add)...)
	if val != nil {
		cpy := buf[len:]
		for i := range cpy {
			cpy[i] = val
		}
	}
	*tab = buf
	return old
}
