// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xfunc_unwind_by_unreachable_b0c4b4() {
	panic("unreachable")
}
func (m *Module) Xfunc_unwind_by_br_1xdk0bc() {
	return
}
func (m *Module) Xfunc_unwind_by_br_value_1xih067() int32 {
	return i32(9)
}
func (m *Module) Xfunc_unwind_by_br_if_kmjzi1() {
	if i32(1) != 0 {
		return
	}
	_ = i64(1)
	_ = i32(3)
}
func (m *Module) Xfunc_unwind_by_br_if_value_1xur0wy() int32 {
	if i32(1) != 0 {
		return i32(9)
	}
	_ = i32(9)
	_ = i64(1)
	return i32(3)
}
func (m *Module) Xfunc_unwind_by_br_table_ie0l6o() {
	switch i32(0) {
	default:
		return
	}
}
func (m *Module) Xfunc_unwind_by_br_table_value_1i8t238() int32 {
	switch i32(0) {
	default:
		return i32(9)
	}
}
func (m *Module) Xfunc_unwind_by_return_15kuc3k() int32 {
	return i32(9)
}
func (m *Module) Xblock_unwind_by_unreachable_k7fi3t() {
	{
		panic("unreachable")
	}
}
func (m *Module) Xblock_unwind_by_br_173i0ct() int32 {
	{
		goto l0
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_unwind_by_br_value_yzb9yc() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_br_if_1f3d6k1() int32 {
	{
		if i32(1) != 0 {
			goto l0
		}
		_ = i64(1)
		_ = i32(3)
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_unwind_by_br_if_value_159ovrv() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			p0 = i32(9)
			goto l0
		}
		_ = i32(9)
		_ = i64(1)
		p0 = i32(3)
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_br_table_1j60yuz() int32 {
	{
		switch i32(0) {
		default:
			goto l0
		}
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_unwind_by_br_table_value_dpu5ik() int32 {
	var p0 int32
	_ = p0
	{
		switch i32(0) {
		default:
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_return_8v2fj2() int32 {
	var p0 int32
	_ = p0
	{
		return i32(9)
	}
}
func (m *Module) Xblock_nested_unwind_by_unreachable_3xsms() int32 {
	var p0 int32
	_ = p0
	{
		{
			panic("unreachable")
		}
	}
}
func (m *Module) Xblock_nested_unwind_by_br_12v85r7() int32 {
	{
		{
			goto l0
		}
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_value_18gvu86() int32 {
	var p0 int32
	_ = p0
	{
		{
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_br_if_1r3fct0() int32 {
	{
		{
			if i32(1) != 0 {
				goto l0
			}
			_ = i64(1)
		}
		_ = i32(3)
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_if_value_1p1y7wm() int32 {
	var p0 int32
	_ = p0
	{
		{
			if i32(1) != 0 {
				p0 = i32(9)
				goto l0
			}
			_ = i32(9)
			_ = i64(1)
		}
		p0 = i32(3)
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_br_table_6sxu3d() int32 {
	{
		{
			switch i32(1) {
			default:
				goto l0
			}
		}
	}
l0:
	return i32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_table_value_zcvzvk() int32 {
	var p0 int32
	_ = p0
	{
		{
			switch i32(1) {
			default:
				p0 = i32(9)
				goto l0
			}
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_return_1jvxl8k() int32 {
	var p0 int32
	_ = p0
	{
		{
			return i32(9)
		}
	}
}
func (m *Module) Xunary_after_unreachable_besty6() int32 {
	panic("unreachable")
}
func (m *Module) Xunary_after_br_1xo853b() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xunary_after_br_if_aooa5a() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			p0 = i32(9)
			goto l0
		}
		_ = i32(9)
		var p1 int32
		if i64(0) == 0 {
			p1 = 1
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xunary_after_br_table_e0oppk() int32 {
	var p0 int32
	_ = p0
	{
		switch i32(0) {
		default:
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xunary_after_return_r4g5b0() int32 {
	return i32(9)
}
func (m *Module) Xbinary_after_unreachable_1gy9sro() int32 {
	panic("unreachable")
}
func (m *Module) Xbinary_after_br_1r5scun() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_br_if_wnmcwl() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			p0 = i32(9)
			goto l0
		}
		_ = i32(9)
		var p1 int32
		if i64(0) == i64(1) {
			p1 = 1
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_br_table_1bfjmgh() int32 {
	var p0 int32
	_ = p0
	{
		switch i32(0) {
		default:
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_return_y3wo8n() int32 {
	return i32(9)
}
func (m *Module) Xselect_after_unreachable_1h9jpid() int32 {
	panic("unreachable")
}
func (m *Module) Xselect_after_br_1pu0fpp() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xselect_after_br_if_3x7c4a() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			p0 = i32(9)
			goto l0
		}
		_ = i32(9)
		p1 := i32(1)
		if i32(0) != 0 {
			p1 = i32(0)
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xselect_after_br_table_mm9swq() int32 {
	var p0 int32
	_ = p0
	{
		switch i32(0) {
		default:
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xselect_after_return_1s3pzrk() int32 {
	return i32(9)
}
func (m *Module) Xblock_value_after_unreachable_rqm3bf() int32 {
	var p0 int32
	_ = p0
	{
		panic("unreachable")
	}
}
func (m *Module) Xblock_value_after_br_jjlj3s() int32 {
	var p0 int32
	_ = p0
	{
		p0 = i32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_br_if_1pny9t1() int32 {
	var p0 int32
	_ = p0
	{
		if i32(1) != 0 {
			p0 = i32(9)
			goto l0
		}
		_ = i32(9)
		p0 = i32(0)
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_br_table_156xog3() int32 {
	var p0 int32
	_ = p0
	{
		switch i32(0) {
		default:
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_return_1220mvm() int32 {
	var p0 int32
	_ = p0
	{
		return i32(9)
	}
}
func (m *Module) Xloop_value_after_unreachable_1fw38ej() int32 {
	var p0 int32
	_ = p0
	{
		panic("unreachable")
	}
}
func (m *Module) Xloop_value_after_br_gbgm7a() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p0 = i32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_br_if_7o1mpx() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			if i32(1) != 0 {
				p0 = i32(9)
				goto l0
			}
			_ = i32(9)
			p1 = i32(0)
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_br_table_i3ca0c() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			switch i32(0) {
			default:
				p0 = i32(9)
				goto l0
			}
		}
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_return_1sf27ss() int32 {
	var p0 int32
	_ = p0
	{
		return i32(9)
	}
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func f32(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
