// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "runtime"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xfunc_unwind_by_unreachable() {
	panic("unreachable")
}
func (m *Module) Xfunc_unwind_by_br() {
	return
}
func (m *Module) Xfunc_unwind_by_br_value() int32 {
	return int32(9)
}
func (m *Module) Xfunc_unwind_by_br_if() {
	if int32(1) != 0 {
		return
	}
	_ = int64(1)
	_ = int32(3)
}
func (m *Module) Xfunc_unwind_by_br_if_value() int32 {
	if int32(1) != 0 {
		return int32(9)
	}
	_ = int32(9)
	_ = int64(1)
	return int32(3)
}
func (m *Module) Xfunc_unwind_by_br_table() {
	switch i32_const(0) {
	default:
		return
	}
}
func (m *Module) Xfunc_unwind_by_br_table_value() int32 {
	switch i32_const(0) {
	default:
		return int32(9)
	}
}
func (m *Module) Xfunc_unwind_by_return() int32 {
	return int32(9)
}
func (m *Module) Xblock_unwind_by_unreachable() {
	{
		panic("unreachable")
	}
}
func (m *Module) Xblock_unwind_by_br() int32 {
	{
		goto l0
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_unwind_by_br_value() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_br_if() int32 {
	{
		if int32(1) != 0 {
			goto l0
		}
		_ = int64(1)
		_ = int32(3)
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_unwind_by_br_if_value() int32 {
	var p0 int32
	_ = p0
	{
		if int32(1) != 0 {
			p0 = int32(9)
			goto l0
		}
		_ = int32(9)
		_ = int64(1)
		p0 = int32(3)
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_br_table() int32 {
	{
		switch i32_const(0) {
		default:
			goto l0
		}
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_unwind_by_br_table_value() int32 {
	var p0 int32
	_ = p0
	{
		switch i32_const(0) {
		default:
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_unwind_by_return() int32 {
	var p0 int32
	_ = p0
	{
		return int32(9)
	}
}
func (m *Module) Xblock_nested_unwind_by_unreachable() int32 {
	var p0 int32
	_ = p0
	{
		{
			panic("unreachable")
		}
	}
}
func (m *Module) Xblock_nested_unwind_by_br() int32 {
	{
		{
			goto l0
		}
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_value() int32 {
	var p0 int32
	_ = p0
	{
		{
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_br_if() int32 {
	{
		{
			if int32(1) != 0 {
				goto l0
			}
			_ = int64(1)
		}
		_ = int32(3)
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_if_value() int32 {
	var p0 int32
	_ = p0
	{
		{
			if int32(1) != 0 {
				p0 = int32(9)
				goto l0
			}
			_ = int32(9)
			_ = int64(1)
		}
		p0 = int32(3)
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_br_table() int32 {
	{
		{
			switch int32(1) {
			default:
				goto l0
			}
		}
	}
l0:
	return int32(9)
}
func (m *Module) Xblock_nested_unwind_by_br_table_value() int32 {
	var p0 int32
	_ = p0
	{
		{
			switch int32(1) {
			default:
				p0 = int32(9)
				goto l0
			}
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_nested_unwind_by_return() int32 {
	var p0 int32
	_ = p0
	{
		{
			return int32(9)
		}
	}
}
func (m *Module) Xunary_after_unreachable() int32 {
	panic("unreachable")
}
func (m *Module) Xunary_after_br() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xunary_after_br_if() int32 {
	var p0 int32
	_ = p0
	{
		if int32(1) != 0 {
			p0 = int32(9)
			goto l0
		}
		_ = int32(9)
		var p1 int32
		if i64_const(0) == 0 {
			p1 = 1
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xunary_after_br_table() int32 {
	var p0 int32
	_ = p0
	{
		switch i32_const(0) {
		default:
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xunary_after_return() int32 {
	return int32(9)
}
func (m *Module) Xbinary_after_unreachable() int32 {
	panic("unreachable")
}
func (m *Module) Xbinary_after_br() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_br_if() int32 {
	var p0 int32
	_ = p0
	{
		if int32(1) != 0 {
			p0 = int32(9)
			goto l0
		}
		_ = int32(9)
		var p1 int32
		if i64_const(0) == int64(1) {
			p1 = 1
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_br_table() int32 {
	var p0 int32
	_ = p0
	{
		switch i32_const(0) {
		default:
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xbinary_after_return() int32 {
	return int32(9)
}
func (m *Module) Xselect_after_unreachable() int32 {
	panic("unreachable")
}
func (m *Module) Xselect_after_br() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xselect_after_br_if() int32 {
	var p0 int32
	_ = p0
	{
		if int32(1) != 0 {
			p0 = int32(9)
			goto l0
		}
		_ = int32(9)
		p1 := int32(1)
		if i32_const(0) != 0 {
			p1 = i32_const(0)
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xselect_after_br_table() int32 {
	var p0 int32
	_ = p0
	{
		switch i32_const(0) {
		default:
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xselect_after_return() int32 {
	return int32(9)
}
func (m *Module) Xblock_value_after_unreachable() int32 {
	var p0 int32
	_ = p0
	{
		panic("unreachable")
	}
}
func (m *Module) Xblock_value_after_br() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(9)
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_br_if() int32 {
	var p0 int32
	_ = p0
	{
		if int32(1) != 0 {
			p0 = int32(9)
			goto l0
		}
		_ = int32(9)
		p0 = i32_const(0)
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_br_table() int32 {
	var p0 int32
	_ = p0
	{
		switch i32_const(0) {
		default:
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xblock_value_after_return() int32 {
	var p0 int32
	_ = p0
	{
		return int32(9)
	}
}
func (m *Module) Xloop_value_after_unreachable() int32 {
	var p0 int32
	_ = p0
	{
		panic("unreachable")
	}
}
func (m *Module) Xloop_value_after_br() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			p0 = int32(9)
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_br_if() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			if int32(1) != 0 {
				p0 = int32(9)
				goto l0
			}
			_ = int32(9)
			p1 = i32_const(0)
		}
		p0 = p1
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_br_table() int32 {
	var p0 int32
	_ = p0
	{
		var p1 int32
		_ = p1
		{
			switch i32_const(0) {
			default:
				p0 = int32(9)
				goto l0
			}
		}
	}
l0:
	return p0
}
func (m *Module) Xloop_value_after_return() int32 {
	var p0 int32
	_ = p0
	{
		return int32(9)
	}
}

//go:nosplit
func i32_const(x int32) int32 { return x }

//go:nosplit
func i64_const(x int64) int64 { return x }

//go:nosplit
func f32_const(x float32) float32 {
	runtime.KeepAlive(&x)
	return x
}

//go:nosplit
func f64_const(x float64) float64 {
	runtime.KeepAlive(&x)
	return x
}
