// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xf32_recoding_eq(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 == t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xf32_recoding_le(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 <= t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xf32_recoding_lt(v0 float32, v1 float32) int32 {
	t0 := v0
	t1 := v1
	t2 := float32(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 < t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xf64_recoding_eq(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	t2 := float64(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 == t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xf64_recoding_le(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	t2 := float64(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 <= t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xf64_recoding_lt(v0 float64, v1 float64) int32 {
	t0 := v0
	t1 := v1
	t2 := float64(t0 * t1)
	t3 := v0
	var t4 int32
	if t2 < t3 {
		t4 = 1
	}
	return t4
}
func (m *Module) Xrecoding_demote(v0 float64, v1 float32) float32 {
	t0 := v0
	t1 := float32(t0)
	t2 := v1
	t3 := float32(t1 * t2)
	return t3
}
