// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math/bits"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	g0       int32
}

func New() *Module {
	m := &Module{}
	m.t0 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.f61}}
	copy(m.t0[0:], m.elements[0])
	m.g0 = i32_const(0)
	return m
}
func (m *Module) f0() {
}
func (m *Module) f1(v0 int32, v1 int32, v2 int32) int32 {
	return v0 + (v1 - v2)
}
func (m *Module) Xas응2Dfunc응2Dfirst() int32 {
	return int32(1)
}
func (m *Module) Xas응2Dfunc응2Dmid() int32 {
	m.f0()
	return int32(2)
}
func (m *Module) Xas응2Dfunc응2Dlast() int32 {
	m.f0()
	return int32(3)
}
func (m *Module) Xas응2Dfunc응2Deverywhere() int32 {
	m.f0()
	return int32(4)
}
func (m *Module) Xas응2Ddrop응2Dfirst(v0 int32) {
	_ = v0
}
func (m *Module) Xas응2Ddrop응2Dlast(v0 int32) {
	_ = v0
}
func (m *Module) Xas응2Ddrop응2Deverywhere(v0 int32) {
	_ = v0
}
func (m *Module) Xas응2Dselect응2Dfirst(v0 int32) int32 {
	p0 := v0
	if v0 != 0 {
		p0 = v0
	}
	return p0
}
func (m *Module) Xas응2Dselect응2Dmid1(v0 int32) int32 {
	p0 := v0
	if v0 != 0 {
		p0 = v0
	}
	return p0
}
func (m *Module) Xas응2Dselect응2Dmid2(v0 int32) int32 {
	p0 := v0
	if v0 != 0 {
		p0 = v0
	}
	return p0
}
func (m *Module) Xas응2Dselect응2Dlast(v0 int32) int32 {
	p0 := v0
	if v0 != 0 {
		p0 = v0
	}
	return p0
}
func (m *Module) Xas응2Dselect응2Deverywhere(v0 int32) int32 {
	p0 := v0
	if v0 != 0 {
		p0 = v0
	}
	return p0
}
func (m *Module) Xas응2Dblock응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas응2Dblock응2Dmid() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas응2Dblock응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(3)
	}
	return p0
}
func (m *Module) Xas응2Dblock응2Deverywhere() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(4)
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Dmid() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(2)
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(3)
	}
	return p0
}
func (m *Module) Xas응2Dloop응2Deverywhere() int32 {
	var p0 int32
	_ = p0
	{
		m.f0()
		p0 = int32(4)
	}
	return p0
}
func (m *Module) Xas응2Dif응2Dcondition(v0 int32) {
	if v0 != 0 {
		m.f0()
	}
}
func (m *Module) Xas응2Dif응2Dthen(v0 int32) {
	if v0 != 0 {
	} else {
		m.f0()
	}
}
func (m *Module) Xas응2Dif응2Delse(v0 int32) {
	if v0 != 0 {
		m.f0()
	} else {
	}
}
func (m *Module) Xas응2Dbr응2Dfirst(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr응2Dlast(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr응2Deverywhere(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		p0 = t1
		goto l0
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_if응2Dfirst(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if v0 != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_if응2Dmid(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if v0 != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_if응2Dlast(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if v0 != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_if응2Deverywhere(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		if v0 != 0 {
			p0 = t1
			goto l0
		}
		p0 = t1
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Dfirst(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		switch v0 {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Dmid(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		switch v0 {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Dlast(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		switch v0 {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas응2Dbr_table응2Deverywhere(v0 int32) int32 {
	var p0 int32
	_ = p0
	{
		t1 := v0
		switch v0 {
		default:
			p0 = t1
			goto l0
		}
	}
l0:
	return p0
}
func (m *Module) Xas응2Dreturn응2Dfirst(v0 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dreturn응2Dlast(v0 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dreturn응2Deverywhere(v0 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dcall응2Dfirst(v0 int32, v1 int32, v2 int32) int32 {
	t0 := m.f1(v0, v1, v2)
	return t0
}
func (m *Module) Xas응2Dcall응2Dmid1(v0 int32, v1 int32, v2 int32) int32 {
	t0 := m.f1(v0, v1, v2)
	return t0
}
func (m *Module) Xas응2Dcall응2Dmid2(v0 int32, v1 int32, v2 int32) int32 {
	t0 := m.f1(v0, v1, v2)
	return t0
}
func (m *Module) Xas응2Dcall응2Dlast(v0 int32, v1 int32, v2 int32) int32 {
	t0 := m.f1(v0, v1, v2)
	return t0
}
func (m *Module) Xas응2Dcall응2Deverywhere(v0 int32, v1 int32, v2 int32) int32 {
	t0 := m.f1(v0, v1, v2)
	return t0
}
func (m *Module) Xas응2Dunary응2Dfirst(v0 int32) int32 {
	return int32(bits.TrailingZeros32(uint32(v0)))
}
func (m *Module) Xas응2Dunary응2Dlast(v0 int32) int32 {
	return int32(bits.TrailingZeros32(uint32(v0)))
}
func (m *Module) Xas응2Dunary응2Deverywhere(v0 int32) int32 {
	return int32(bits.TrailingZeros32(uint32(v0)))
}
func (m *Module) Xas응2Dbinary응2Dfirst(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xas응2Dbinary응2Dmid(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xas응2Dbinary응2Dlast(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xas응2Dbinary응2Deverywhere(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xas응2Dtest응2Dfirst(v0 int32) int32 {
	var p0 int32
	if v0 == 0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dtest응2Dlast(v0 int32) int32 {
	var p0 int32
	if v0 == 0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dtest응2Deverywhere(v0 int32) int32 {
	var p0 int32
	if v0 == 0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dcompare응2Dfirst(v0 int32) int32 {
	var p0 int32
	if v0 != v0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dcompare응2Dmid(v0 int32) int32 {
	var p0 int32
	if v0 != v0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dcompare응2Dlast(v0 int32) int32 {
	var p0 int32
	if uint32(v0) < uint32(v0) {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dcompare응2Deverywhere(v0 int32) int32 {
	var p0 int32
	if v0 <= v0 {
		p0 = 1
	}
	return p0
}
func (m *Module) Xas응2Dmemory응2Egrow응2Dfirst(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xas응2Dmemory응2Egrow응2Dlast(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xas응2Dmemory응2Egrow응2Deverywhere(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) f61(v0 int32, v1 int32) int32 {
	return v0
}
func (m *Module) Xas응2Dcall_indirect응2Dfirst() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Dmid1() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Dmid2() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Dlast() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dcall_indirect응2Deverywhere() int32 {
	var p0 int32
	_ = p0
	{
		t1 := m.t0[uint(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		p0 = t1
	}
	return p0
}
func (m *Module) Xas응2Dlocal응2Eset응2Dfirst(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dlocal응2Eset응2Dlast(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dlocal응2Eset응2Deverywhere(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dlocal응2Etee응2Dfirst(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dlocal응2Etee응2Dlast(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dlocal응2Etee응2Deverywhere(v0 int32) int32 {
	v0 = int32(2)
	return v0
}
func (m *Module) Xas응2Dglobal응2Eset응2Dfirst() int32 {
	m.g0 = int32(2)
	t0 := m.g0
	return t0
}
func (m *Module) Xas응2Dglobal응2Eset응2Dlast() int32 {
	m.g0 = int32(2)
	t0 := m.g0
	return t0
}
func (m *Module) Xas응2Dglobal응2Eset응2Deverywhere() int32 {
	m.g0 = int32(2)
	t0 := m.g0
	return t0
}
func (m *Module) Xas응2Dload응2Dfirst(v0 int32) int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) Xas응2Dload응2Dlast(v0 int32) int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) Xas응2Dload응2Deverywhere(v0 int32) int32 {
	t0 := int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) Xas응2Dstore응2Dfirst(v0 int32, v1 int32) {
	binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v1))
}
func (m *Module) Xas응2Dstore응2Dmid(v0 int32, v1 int32) {
	binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v1))
}
func (m *Module) Xas응2Dstore응2Dlast(v0 int32, v1 int32) {
	binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v1))
}
func (m *Module) Xas응2Dstore응2Deverywhere(v0 int32, v1 int32) {
	binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v1))
}

//go:nosplit
func i32_const(x int32) int32 { return x }

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
