// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math/bits"
)

type Module struct {
	table    []any
	elements [][]any
	memory   []byte
	maxMem   int32
	_a       int32
}

func New() *Module {
	m := &Module{}
	m.table = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{[]any{m._func}}
	copy(m.table[0:], m.elements[0])
	m._a = i32_const(0)
	return m
}
func (m *Module) _dummy() {
}
func (m *Module) _3_ary(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := t1 - t2
	t4 := t0 + t3
	return t4
}
func (m *Module) Xas_func_first() int32 {
	return int32(1)
}
func (m *Module) Xas_func_mid() int32 {
	m._dummy()
	return int32(2)
}
func (m *Module) Xas_func_last() int32 {
	m._dummy()
	return int32(3)
}
func (m *Module) Xas_func_everywhere() int32 {
	m._dummy()
	return int32(4)
}
func (m *Module) Xas_drop_first(v0 int32) {
	t0 := v0
	_ = t0
}
func (m *Module) Xas_drop_last(v0 int32) {
	t0 := v0
	_ = t0
}
func (m *Module) Xas_drop_everywhere(v0 int32) {
	t0 := v0
	_ = t0
}
func (m *Module) Xas_select_first(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := t1
	if t2 != 0 {
		t3 = t0
	}
	return t3
}
func (m *Module) Xas_select_mid1(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := t1
	if t2 != 0 {
		t3 = t0
	}
	return t3
}
func (m *Module) Xas_select_mid2(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := t1
	if t2 != 0 {
		t3 = t0
	}
	return t3
}
func (m *Module) Xas_select_last(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := t1
	if t2 != 0 {
		t3 = t0
	}
	return t3
}
func (m *Module) Xas_select_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := v0
	t3 := t1
	if t2 != 0 {
		t3 = t0
	}
	return t3
}
func (m *Module) Xas_block_first() int32 {
	var t0 int32
	_ = t0
	{
		t0 = int32(2)
	}
	return t0
}
func (m *Module) Xas_block_mid() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(2)
	}
	return t0
}
func (m *Module) Xas_block_last() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(3)
	}
	return t0
}
func (m *Module) Xas_block_everywhere() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(4)
	}
	return t0
}
func (m *Module) Xas_loop_first() int32 {
	var t0 int32
	_ = t0
	{
		t0 = int32(2)
	}
	return t0
}
func (m *Module) Xas_loop_mid() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(2)
	}
	return t0
}
func (m *Module) Xas_loop_last() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(3)
	}
	return t0
}
func (m *Module) Xas_loop_everywhere() int32 {
	var t0 int32
	_ = t0
	{
		m._dummy()
		t0 = int32(4)
	}
	return t0
}
func (m *Module) Xas_if_condition(v0 int32) {
	t0 := v0
	if t0 != 0 {
		m._dummy()
	}
}
func (m *Module) Xas_if_then(v0 int32) {
	t0 := v0
	if t0 != 0 {
	} else {
		m._dummy()
	}
}
func (m *Module) Xas_if_else(v0 int32) {
	t0 := v0
	if t0 != 0 {
		m._dummy()
	} else {
	}
}
func (m *Module) Xas_br_first(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t0 = t1
		goto l0
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_last(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t0 = t1
		goto l0
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_everywhere(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t0 = t1
		goto l0
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_if_first(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		if t2 != 0 {
			goto l0
		}
		t0 = t1
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_if_mid(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		if t2 != 0 {
			goto l0
		}
		t0 = t1
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_if_last(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		if t2 != 0 {
			goto l0
		}
		t0 = t1
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_if_everywhere(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		if t2 != 0 {
			goto l0
		}
		t0 = t1
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_table_first(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		t0 = t1
		switch t2 {
		default:
			goto l0
		case 0:
			goto l0
		}
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_table_mid(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		t0 = t1
		switch t2 {
		default:
			goto l0
		case 0:
			goto l0
		}
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_table_last(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		t0 = t1
		switch t2 {
		default:
			goto l0
		case 0:
			goto l0
		}
	}
l0:
	;
	return t0
}
func (m *Module) Xas_br_table_everywhere(v0 int32) int32 {
	var t0 int32
	_ = t0
	{
		t1 := v0
		t2 := v0
		t0 = t1
		t0 = t1
		switch t2 {
		default:
			goto l0
		case 0:
			goto l0
		}
	}
l0:
	;
	return t0
}
func (m *Module) Xas_return_first(v0 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_return_last(v0 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_return_everywhere(v0 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_call_first(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := m._3_ary(t0, t1, t2)
	return t3
}
func (m *Module) Xas_call_mid1(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := m._3_ary(t0, t1, t2)
	return t3
}
func (m *Module) Xas_call_mid2(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := m._3_ary(t0, t1, t2)
	return t3
}
func (m *Module) Xas_call_last(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := m._3_ary(t0, t1, t2)
	return t3
}
func (m *Module) Xas_call_everywhere(v0 int32, v1 int32, v2 int32) int32 {
	t0 := v0
	t1 := v1
	t2 := v2
	t3 := m._3_ary(t0, t1, t2)
	return t3
}
func (m *Module) Xas_unary_first(v0 int32) int32 {
	t0 := v0
	t1 := int32(bits.TrailingZeros32(uint32(t0)))
	return t1
}
func (m *Module) Xas_unary_last(v0 int32) int32 {
	t0 := v0
	t1 := int32(bits.TrailingZeros32(uint32(t0)))
	return t1
}
func (m *Module) Xas_unary_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := int32(bits.TrailingZeros32(uint32(t0)))
	return t1
}
func (m *Module) Xas_binary_first(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := t0 + t1
	return t2
}
func (m *Module) Xas_binary_mid(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := t0 + t1
	return t2
}
func (m *Module) Xas_binary_last(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := t0 + t1
	return t2
}
func (m *Module) Xas_binary_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := v0
	t2 := t0 + t1
	return t2
}
func (m *Module) Xas_test_first(v0 int32) int32 {
	t0 := v0
	var t1 int32
	if t0 == 0 {
		t1 = 1
	}
	return t1
}
func (m *Module) Xas_test_last(v0 int32) int32 {
	t0 := v0
	var t1 int32
	if t0 == 0 {
		t1 = 1
	}
	return t1
}
func (m *Module) Xas_test_everywhere(v0 int32) int32 {
	t0 := v0
	var t1 int32
	if t0 == 0 {
		t1 = 1
	}
	return t1
}
func (m *Module) Xas_compare_first(v0 int32) int32 {
	t0 := v0
	t1 := v0
	var t2 int32
	if t0 != t1 {
		t2 = 1
	}
	return t2
}
func (m *Module) Xas_compare_mid(v0 int32) int32 {
	t0 := v0
	t1 := v0
	var t2 int32
	if t0 != t1 {
		t2 = 1
	}
	return t2
}
func (m *Module) Xas_compare_last(v0 int32) int32 {
	t0 := v0
	t1 := v0
	var t2 int32
	if uint32(t0) < uint32(t1) {
		t2 = 1
	}
	return t2
}
func (m *Module) Xas_compare_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := v0
	var t2 int32
	if t0 <= t1 {
		t2 = 1
	}
	return t2
}
func (m *Module) Xas_memory_grow_first(v0 int32) int32 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}
func (m *Module) Xas_memory_grow_last(v0 int32) int32 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}
func (m *Module) Xas_memory_grow_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := memory_grow(&m.memory, t0, m.maxMem)
	return t1
}
func (m *Module) _func(v0 int32, v1 int32) int32 {
	t0 := v0
	return t0
}
func (m *Module) Xas_call_indirect_first() int32 {
	var t0 int32
	_ = t0
	{
		t1 := m.table[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		t0 = t1
	}
	return t0
}
func (m *Module) Xas_call_indirect_mid1() int32 {
	var t0 int32
	_ = t0
	{
		t1 := m.table[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		t0 = t1
	}
	return t0
}
func (m *Module) Xas_call_indirect_mid2() int32 {
	var t0 int32
	_ = t0
	{
		t1 := m.table[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		t0 = t1
	}
	return t0
}
func (m *Module) Xas_call_indirect_last() int32 {
	var t0 int32
	_ = t0
	{
		t1 := m.table[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		t0 = t1
	}
	return t0
}
func (m *Module) Xas_call_indirect_everywhere() int32 {
	var t0 int32
	_ = t0
	{
		t1 := m.table[uint32(i32_const(0))].(func(v0 int32, v1 int32) int32)(int32(1), int32(2))
		t0 = t1
	}
	return t0
}
func (m *Module) Xas_local_set_first(v0 int32) int32 {
	v0 = int32(2)
	t0 := v0
	return t0
}
func (m *Module) Xas_local_set_last(v0 int32) int32 {
	v0 = int32(2)
	t0 := v0
	return t0
}
func (m *Module) Xas_local_set_everywhere(v0 int32) int32 {
	v0 = int32(2)
	t0 := v0
	return t0
}
func (m *Module) Xas_local_tee_first(v0 int32) int32 {
	v0 = int32(2)
	return int32(2)
}
func (m *Module) Xas_local_tee_last(v0 int32) int32 {
	v0 = int32(2)
	return int32(2)
}
func (m *Module) Xas_local_tee_everywhere(v0 int32) int32 {
	v0 = int32(2)
	return int32(2)
}
func (m *Module) Xas_global_set_first() int32 {
	m._a = int32(2)
	t0 := m._a
	return t0
}
func (m *Module) Xas_global_set_last() int32 {
	m._a = int32(2)
	t0 := m._a
	return t0
}
func (m *Module) Xas_global_set_everywhere() int32 {
	m._a = int32(2)
	t0 := m._a
	return t0
}
func (m *Module) Xas_load_first(v0 int32) int32 {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xas_load_last(v0 int32) int32 {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xas_load_everywhere(v0 int32) int32 {
	t0 := v0
	t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(t0):]))
	return t1
}
func (m *Module) Xas_store_first(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}
func (m *Module) Xas_store_mid(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}
func (m *Module) Xas_store_last(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}
func (m *Module) Xas_store_everywhere(v0 int32, v1 int32) {
	t0 := v0
	t1 := v1
	binary.LittleEndian.PutUint32(m.memory[uint32(t0):], uint32(t1))
}

func i32_const(x int32) int32 { return x }

func memory_grow(mem *[]byte, delta, max int32) int32 {
	buf := *mem
	len := len(buf)
	old := int32(len >> 16)
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
