// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "math"

type Module struct {
}

func New() *Module {
	m := &Module{}
	return m
}
func (m *Module) Xi32응2Ediv_s_7(v0 int32) int32 {
	t0 := i32_div_s(v0, int32(7))
	return t0
}
func (m *Module) Xi32응2Ediv_u_7(v0 int32) int32 {
	t0 := int32(uint32(v0) / uint32(int32(7)))
	return t0
}
func (m *Module) Xi64응2Ediv_s_7(v0 int64) int64 {
	t0 := i64_div_s(v0, int64(7))
	return t0
}
func (m *Module) Xi64응2Ediv_u_7(v0 int64) int64 {
	t0 := int64(uint64(v0) / uint64(int64(7)))
	return t0
}

//go:nosplit
func i32_div_s(x, y int32) int32 {
	if y == -1 && x == math.MinInt32 {
		panic("integer overflow")
	}
	return x / y
}

//go:nosplit
func i64_div_s(x, y int64) int64 {
	if y == -1 && x == math.MinInt64 {
		panic("integer overflow")
	}
	return x / y
}
